### ISSUE TITLE
ephemeral vs non-ephemeral interactions: how can the recipient tell the difference?

### ISSUE THREAD

**Issue by llorllale** [decentralized-identity/didcomm-messaging#100]
Point raised by @kdenhartog on today's call:

The mechanics of 0RTT work without assumptions on whether the interaction is "ephemeral" vs. "non-ephemeral".

Since there is currently nothing other can the `from` attribute that contains the DID of the sender: how can the recipient of a message understand that the interaction is happening in "ephemeral" mode and thus apply the correct handling and retention policy for the DID received in the message?

**Comment by TelegramSam** [comment]
More generally, how does the other party know that the relationship is 'done'?

Every interaction can have a variable lifetime, and there isn't a good binary split between 'ephemeral' and 'non-ephemeral'. An interaction can have 2 messages, 4000, or anywhere in between. I think more often than not, the final length of the interaction isn't known till it's all done.

Should we define a way to single the end of an interaction, as a courtesy to the other party? Should this be part of the spec?

**Comment by TelegramSam** [comment]
We've used the word interaction, but I'm not quite sure that's the right one.

What I'm talking about is the death of the DID I gave you. After it 'dies', then the keys and service endpoint are no longer expected to work.

**Comment by kdenhartog** [comment]
Daniel brought up a good point on the WG call today that we could use a null value to handle this. We agreed that the idea is worth exploring further and were going to go away and think a bit more about how this might be useful.

**Comment by TelegramSam** [comment]
Proposed details of 'ending' a relationship by using the DID Rotation Mechanism to rotate your sender DID to null:
Create a `from_prior` header using 'null' as the new DID value. This is signed by the prior DID key.
Use 'null' as the `from` attribute on the message. Encrypt the message using any key. 
We declare that any key is authorized for the null sender. 

Notes:
This uses 'null' as a special case. I don't love this.
This method is not detectable prior to decryption by recipient.
This method introduces kind of another way to send an ephemeral message, unless we declare that this MUST only happen with a null message type.

**Comment by llorllale** [comment]
@TelegramSam 

>  Create a from_prior header using 'null' as the new DID value. This is signed by the prior DID key.

Can we be a bit more specific on the structure of the signature and what exactly is signed?

**Comment by TelegramSam** [comment]
Notes from WG meeting: Omit the sub in the from_prior JWT, from = "None"

**Comment by kdenhartog** [comment]
`from` is optional now. Is this no longer relevant now?

**Comment by TelegramSam** [comment]
The concept of rotating to None as a way of closing down the relationship is not yet reflected in the spec. An addition to the from_prior section would satisfy that need.
