### ISSUE TITLE
references.md: ISO specs

### ISSUE THREAD

**Issue by dhh1128** [decentralized-identity/didcomm-messaging#11]
@awoie commented, in relation to references:

>add ISO 18013-5 ? NFC -> BLE/Wifi-Direct, QR Code -> BLE/Wifi-Direct

**Comment by kdenhartog** [comment]
Don't think this is needed anymore. Marking as pending close.

**Comment by awoie** [comment]
yep, i think we can close this. adding ISO 18013-5 might be out of scope anyways.

**Comment by kdenhartog** [comment]
Yeah, I didn't put the justification down that I was originally thinking but in my mind we could define these as a method of transport which meant we didn't need to focus on it to get v2. Additionally, I thought it would be up to whoever wants that work to make it happen so they can decide how they want it done.

**Comment by TelegramSam** [comment]
This is the subject of a transport extension, not directly related to DIDComm core concerns.
Closed via discussion in WG meeting 20210802. Please reopen if it should not have been resolved.
