### ISSUE TITLE
"Composability" Issue

### ISSUE THREAD

**Issue by downTheFallLine** [decentralized-identity/didcomm-messaging#110]
The draft language focuses on choice of crypto suite-- i.e., "pick the crypto suite and features you need, without incurring overwhelming dependencies for stuff you don’t".

Is the concept of composability limited to choice of crypto suites?   Or are there other elements which would fall into the composability concept?  If so, what are they?

**Comment by TelegramSam** [comment]
I think crypto suites are the only one directly within the core spec.

Another important aspect is which protocols are supported. There are only a few 'core' protocols that must/should be supported, and the rest is open season. One of the 'core' protocols allows discovery of supported protocols. This does happen after the secure connection is created.

**Comment by kdenhartog** [comment]
Think this is no longer needed. Going to mark it as pending closed

**Comment by TelegramSam** [comment]
Closed via discussion in WG meeting 20210802. Please reopen if it should not have been resolved.
