### ISSUE TITLE
Sec 3 - to attribute defined as optional

### ISSUE THREAD

**Issue by downTheFallLine** [decentralized-identity/didcomm-messaging#114]
Current specification indicates that to attribute is optional.  If a message is created without a "to", what does that mean?  Should this attribute be required?

**Comment by TelegramSam** [comment]
If the message is signed, but not encrypted, the 'to' may not be known. We could clarify that this MUST be specified in an encrypted message.

**Comment by downTheFallLine** [comment]
I'm still confused.   If a message has no "to" attribute, where does it go?  How would it be routed?  To whom would it be routed?

**Comment by TelegramSam** [comment]
The 'to' attribute is not useful in message that is signed, but not encrypted. This is useful when you want to pass a message to an unknown recipient. A current example is the [Out of Band Invitation](https://identity.foundation/didcomm-messaging/spec/#out-of-band-messages) message which is passed via link or QR code. Other methods are also possible.

Messages without a 'to' attribute are NOT capable of being routed.

**Comment by kdenhartog** [comment]
The `to` value isn't needed for the final recipient of any message irregardless of the envelope format as well. 'to' remains in there for forward messages so that mediators are able to properly route payloads.

**Comment by TelegramSam** [comment]
(WG 20201109.) forward message 'to' attrribute needs a rename. perhaps destination/next?

**Comment by dhh1128** [comment]
I believe this issue can be closed once PR #128 is merged.
