### ISSUE TITLE
Sec 3 - from "attribute" is optional

### ISSUE THREAD

**Issue by downTheFallLine** [decentralized-identity/didcomm-messaging#115]
The spec states "from" as an optional attribute.  If the attribute is missing from a message, and the message is to be encrypted and/or signed, how then does the recipient go about determining key resolution?  Is this handled elsewhere in the spec?  If so, could we at least add a reference in this section?

**Comment by tplooker** [comment]
For instances where the message is [anonymously encrypted](https://identity.foundation/didcomm-messaging/spec/#anonymous-encryption) this attribute would be omitted.

**Comment by TelegramSam** [comment]
Unless we kill anoncrypt. :)

**Comment by downTheFallLine** [comment]
@tplooker then could we add that clarifying language into the spec please?

**Comment by TelegramSam** [comment]
TODO: The text does not yet address how to achieve 'anonymous' communication by using a Peer DID.
We need to address how rotation to a 'null' DID functionally works. (WG 20201109)
