### ISSUE TITLE
Sec 3 - "expires_time" is optional

### ISSUE THREAD

**Issue by downTheFallLine** [decentralized-identity/didcomm-messaging#116]
The spec indicates that "expires_time" is optional.   In the event a message is constructed without this attribute, is there an implied semantic that the message has no expiration.  If so, the implied semantic should be explicitly stated, in my view.

**Comment by tplooker** [comment]
I agree, "expires_time" is optional and the implied semantic meaning of its omission should be stated clearly in the spec.

**Comment by TelegramSam** [comment]
Agree this should be explicit. Currently the JWM profile for DIDComm is a different md doc.  Should that profile be included directly in the spec?

**Comment by downTheFallLine** [comment]
@TelegramSam That's a good catch.  Seems to me if DIDComm is building on top of JWM, and that attribute is defined in JWM, the DIDCOMM spec should not attempt to "redefine" what JWM has already done--- that COULD be a major conflict at some point in the future.  Instead, we'd just be clear that we're building on top of JWM.
