### ISSUE TITLE
For `from` and `from_prior`, use a DID URL (not just DID) and prohibit fragments

### ISSUE THREAD

**Issue by TelegramSam** [decentralized-identity/didcomm-messaging#125]
This provides a did resolution method without dereferencing.

**Comment by awoie** [comment]
@TelegramSam I guess we have addressed this issue? Can we close?

**Comment by kdenhartog** [comment]
Pretty sure we can close this now

**Comment by TelegramSam** [comment]
Closed via discussion in WG meeting 20210802. Please reopen if it should not have been resolved.
