### ISSUE TITLE
Clarification requested: How are DIDDocs for Peer DIDs exchanged?

### ISSUE THREAD

**Issue by TimoGlastra** [decentralized-identity/didcomm-messaging#126]
I’m probably missing something, but how are DIDDocs for peer dids (especially the service part) exchanged in DIDComm v2? I get that the did exchange protocol is removed and the “from” attribute identifies the sender did. However I don’t see any of the other patterns that were used in V1 (did exchange, ~service decorator, service key in oob). I’ve seen some mentions of initial-state and signed-ietf-json-patch, has it something to do with this?

As a side note maybe we can add this to the What's new section for my fellow Aries community members exploring V2 (I'll be happy to raise a PR)

**Comment by TelegramSam** [comment]
to and from allow DIDURL with query parameters (without fragment).
DID methods indicate how query parameters are to be used to pass state information.

**Comment by TimoGlastra** [comment]
Fixed in #131
