### ISSUE TITLE
Size (byte length) Specification for DIDComm Messages

### ISSUE THREAD

**Issue by mccown** [decentralized-identity/didcomm-messaging#135]
In a recent working group call, I asked about maximum message lengths and was told that a max length wasn't specified.  To help agents accommodate potentially large variable length messages, I'm proposing that a length specification with a maximum size be added to DIDComm messages / DIDComm standard.  

Leaving max length undefined creates a situation where an agent will either:  1) receive incoming data until a complete message is received, 2) receive data until an agent-specific maximum is received at which point it terminates the incoming message, or 3) fill the available receiving buffer memory until undefined events occur.  A well-defined agent should not experience #3.

As examples, the IETF RFCs [791](https://tools.ietf.org/html/rfc791) & [2460](https://tools.ietf.org/html/rfc2460) describe maximum packet sizes for IP traffic (64K) and RFC [2675](https://tools.ietf.org/html/rfc2675) also describes a maximum (4GB) 'jumbogram' length. 

Specifying a maximum message limit will help agents process large messages while not leaving them to subjectively determine when a message is 'too big', a potential DOS attack, etc.  Other than those specified by other standards above, I don't have a particular size limit to propose.  

In addition to having a DIDComm-specified max length, this may also be something that individual agents could configure.  For example, a large server could accommodate receiving much larger messages than an IoT device, which may need to specify a smaller maximum DIDComm message size.

**Comment by 35359595** [comment]
This possibly can be a problem for mediators as well - easy to create DOS type attack by flooding the mediator. One of the solutions is to have big payloads `Pull`-ed rather than `Push`-ed. This will coop well with multiple receivers too as payload remains in one copy until actually retrieved by recipient(s).

**Comment by tmarkovski** [comment]
Are you proposing on adding a one single size to limit all messages or a standard that allows this limit to be discoverable?

**Comment by tmarkovski** [comment]
I think this would be a good candidate for a didcomm well known configuration.

**Comment by TelegramSam** [comment]
Discussed in WG 20211101. 
This could be communicated in the Discover Features protocol between peers.
More details around recommendations can be left to future work.

**Comment by TelegramSam** [comment]
@mccown what's the simplest way to solve this with respect to v2?

**Comment by TelegramSam** [comment]
Discussed WG 20220418. Needs more discussion after IIW.
Needs: 
- a defined default max size for all transports. 100k? 1mb? 10mb? (or,no default is specified)
- size expressed in kilobytes.
- behavior if size is exceeded
- How to share max size differences (larger or smaller) via discover features, (MUST)
- Same size for all transports.
- Transport defined responses for message rejected to size.

**Comment by TelegramSam** [comment]
Associated PR merged.
