### ISSUE TITLE
Need a DIDComm version translator script (v1 <--> v2)

### ISSUE THREAD

**Issue by dhh1128** [decentralized-identity/didcomm-messaging#136]
This issue tracks a sister issue in Hyperledger Aries: https://github.com/hyperledger/aries-rfcs/issues/578

**Comment by kdenhartog** [comment]
@dhh1128 thinking this may fit better into gemini. Thoughts on closing this here and handling it as an implementation detail?

**Comment by dhh1128** [comment]
I agree that it's pretty different from the spec work that the WG has focused on.

Gemini might make sense as a home. I'll move it there.

**Comment by dhh1128** [comment]
Moved to https://github.com/sicpa-dlab/didcomm-gemini/issues/55
