### ISSUE TITLE
Add section for Decorators (headers)

### ISSUE THREAD

**Issue by awoie** [decentralized-identity/didcomm-messaging#142]
General message constructs section is missing decorators / headers section.

**Comment by kdenhartog** [comment]
Going to focus this topic on the specific area of defining best practices for how to use and define headers. Related to this discussion is #223

@dhh1128 alerting this to you based on your comment here https://github.com/decentralized-identity/didcomm-messaging/issues/223#issuecomment-876501069

**Comment by kdenhartog** [comment]
Quote replying @dhh1128 comment from #137 here to consolidate the issues

> Presumably, putting something in a header means we think it's of general interest to many message types, and its semantics can be fully defined in isolation.
> 
> However, we think people might be tempted to overuse headers. Need to explain the tradeoffs.
