### ISSUE TITLE
Add section for Timing

### ISSUE THREAD

**Issue by awoie** [decentralized-identity/didcomm-messaging#146]
General message constructs section is missing Timing section

**Comment by TelegramSam** [comment]
this may not be needed with the sent time and expires time as top level headers.

**Comment by TelegramSam** [comment]
@awoie are the existing headers sufficient?

**Comment by TelegramSam** [comment]
Discussed WG 20220131. Headers currently in spec are not sufficient for anything beyond basic needs. More detailed timing work within the base spec is left to work beyond this verion.
