### ISSUE TITLE
Add section for ACKs

### ISSUE THREAD

**Issue by awoie** [decentralized-identity/didcomm-messaging#147]
General message constructs section is missing ACKs section

**Comment by TelegramSam** [comment]
ACKs mentioned here: https://identity.foundation/didcomm-messaging/spec/#acks

In a todo here: https://identity.foundation/didcomm-messaging/spec/#roles

and as an incomplete section here: https://identity.foundation/didcomm-messaging/spec/#general-messaging-constructs

An example is given in the OOB section: https://identity.foundation/didcomm-messaging/spec/#reference-3
Which also contains a link to an Aries RFC: https://github.com/hyperledger/aries-rfcs/blob/main/features/0015-acks/README.md#ack-status

**Comment by TelegramSam** [comment]
Discussed in WG 20220214.
