### ISSUE TITLE
minimal i18n needed

### ISSUE THREAD

**Issue by dhh1128** [decentralized-identity/didcomm-messaging#152]
We need enough i18n support in DIDComm v2 to prevent a variety of incompatible solutions from arising. We should explain how a DIDComm protocol can solve 2 problems:

1. Clarify the lang of a field ("These instructions for the loan applicant are in Spanish.")
2. Allow fields in a message to have the same semantic role, but provide content in different languages. ("Here's the French equivalent of the Spanish instructions field.")

This is likely to require much less complexity than the i18n mechanism proposed for DIDComm v1 -- but perhaps it will use a subset of it?

**Comment by kdenhartog** [comment]
related to #226. Going to close this and quote reply your comment over there to consolidate the discussion.
