### ISSUE TITLE
Work with author to modify ECDH-1PU to encrypt the skid

### ISSUE THREAD

**Issue by kdenhartog** [decentralized-identity/didcomm-messaging#156]
This is an issue to track updates needed in the ECDH-1PU draft that defines that the skid can be optional encrypted with the epk and the static recipient key in order to add sender anonymity (prevents an external party from tracking which senders and recipients are communicating with each other) to ECDH-1PU.

**Comment by awoie** [comment]
@kdenhartog I guess we can close this issue?

**Comment by kdenhartog** [comment]
Closing this for now. I think we've found a resolution to this and if ECDH-1PU decides to add encrypted skid's that will be handled in that repo.
