### ISSUE TITLE
Include details about how DIDComm keys are identified in the DID Document

### ISSUE THREAD

**Issue by llorllale** [decentralized-identity/didcomm-messaging#159]
This issue tracks half of the TODO in section [9.4 of the spec](https://identity.foundation/didcomm-messaging/spec/#did-document-keys):

> TODO: include details about how DIDComm keys are represented/identified in the DID Document. The DID Core Spec appears light on details and examples of keyAgreement keys. Clarifying language should be included here or there.

This [comment](https://github.com/w3c/did-core/issues/599#issuecomment-772828240) triggered this thought - should a sender encrypt to all `keyAgreement` keys in the recipients DID? What if some of those keys are not controlled by the recipient DID's subject?

The spec currently says:

> All keys declared in the DID Document’s keyAgreement section should be used as recipients when encrypting a message.

Note the SHOULD instead of a MUST.

**Comment by OR13** [comment]
I recall the reason for encrypting to all keys listed, was that we can't be sure of where the keys might be (phone, desktop, cloud server)...

This feels a bit wrong in a protocol that is about communication, shouldn't I know if I intend to dial a phone number or an ip address?... and then be able to avoid sending ciphertext over the wire that has been encrypted to many keys which may not be needing the plaintext?

Is there an expectation of exactly once delivery to all locations that might have a private key registered in keyAgreement?

**Comment by llorllale** [comment]
Yes, there are expectations for this with several good use cases:

* convenience: the one you allude to where Alice has a laptop, phone, and tablet
* audit: Daniel's point in https://github.com/w3c/did-core/issues/599
* N-wise comms in a hub-spoke topology

I'm sure there are more.

**Comment by OR13** [comment]
So the concrete proposal is to make the SHOULD a MUST here?  or add additional warning text about accidentally encrypting content for the wrong recipients if people put their keys in the `keyAgreement` section?

**Comment by TelegramSam** [comment]
Fixed in #360

**Comment by TelegramSam** [comment]
#360 merged, so closing this.
