### ISSUE TITLE
All images broken on spec page

### ISSUE THREAD

**Issue by hidde-jan** [decentralized-identity/didcomm-messaging#164]
See: https://identity.foundation/didcomm-messaging/spec/

All images are broken in Chrome.

<img width="433" alt="Screenshot 2021-02-22 at 19 13 19" src="https://user-images.githubusercontent.com/171505/108751044-09583880-7542-11eb-8479-ac3543d03273.png">

**Comment by brianorwhatever** [comment]
rendering fine for me in chrome now
![image](https://user-images.githubusercontent.com/7122708/125839168-dfea0438-1e4c-4c88-94fd-c6423c7a3425.png)
