### ISSUE TITLE
Require always `cty: "JWM"`

### ISSUE THREAD

**Issue by llorllale** [decentralized-identity/didcomm-messaging#165]
The JWM draft's use of [`cty`](https://tools.ietf.org/html/draft-looker-jwm-01#section-4.2) follows that of [RFC7519](https://tools.ietf.org/html/rfc7519#section-5.2), [RFC7516](https://tools.ietf.org/html/rfc7516#section-4.1.12), and [RFC7515](https://tools.ietf.org/html/rfc7515#section-4.1.10), which is to make this parameter optional/NOT RECOMMENDED.

I propose that for DIDComm v2 this header MUST be present (and its value MUST be `JWM` just like the spec says right now).

Doing this allows a cleaner transition V1 -> V2.

Edit: we could specify a separate `cty` for "regular" (ie non-nested) JWMs so as not to clash with the nested ones, which require `JWM`.

**Comment by llorllale** [comment]
@tplooker thoughts on why use of `cty` is not recommended in the absence of a nested JWT?

**Comment by kdenhartog** [comment]
Take a look at this for the nested part. https://github.com/mattrglobal/jwm/issues/46 Does that align with what you're thinking about here?

I think you're right that we should update some of that language to MUSTs as well in favor of some of those SHOULDs I was proposing.

**Comment by llorllale** [comment]
@kdenhartog it aligns fairly well, although I propose we change a SHOULD -> MUST:

> In the normal case in which nested signing or encryption operations are not employed, the use of this Header Parameter ~~SHOULD~~ MUST be "JWM". In the case that nested signing or encryption is employed, this Header Parameter MUST be present; in this case, the value MUST be "JWS" to indicate the payload follows a standard JWS structure. The internal JWS header SHOULD also indicate "JWM".

> Does that align with what you're thinking about here?

What I am trying to do is disentangle all the combinations of `DIDComm service types` vs `mime types` vs `encryption parameters` vs `inner payload format` as we look to move towards V2.

**Comment by kdenhartog** [comment]
I'm definitely aligned with the intent. Thanks for making it happen. As for the change I'm aligned with that language. I think we should change that last SHOULD to a MUST as well. I think that's going to be useful for what you're after too.

**Comment by llorllale** [comment]
> I think we should change that last SHOULD to a MUST as well.

:100:

**Comment by dhh1128** [comment]
I am in favor of requiring `cty`, but I don't think its value should be "JWM." The reason is that JWM doesn't actually tell us that we're dealing with DIDComm plaintext; it could be a JWM that has nothing to do with DIDComm. In other words, I don't think "JWM" is specific enough.

This issue was already tackled in a PR that the community approved (though not in the context of the `cty` header). Here is what our current verbiage says:

>Applications running one or more DIDComm-based protocols may wish to define their own media types for the protocols they support. Absent such customization, the preferred media type for a generic DIDComm plaintext message SHOULD be application/didcomm-plain+json. This correctly conveys the fact that code handling such content functions at a different level from DIDComm’s security and routing, and that generic JSON tools and actions are likely to be a helpful fallback in processing the content.

>DIDComm plaintext messages are also correctly understood as JWM content (see Plaintext Message Structure, below). Thus a media type for JWMs MIGHT be an accurate but more generic way to categorize them. However, not all JWMs are DIDComm messages, so this categorization is suboptimal. Similarly, application/json is true, but overly generic and therefore not recommended.

**Comment by dhh1128** [comment]
(BTW, the JWM spec should not be mandating that content of type JWM is always referred to as a JWM, since JWM explicitly calls for profiles to specialize itself. See [this comment](https://github.com/mattrglobal/jwm/issues/46#issuecomment-796164201).)

**Comment by kdenhartog** [comment]
+1 We should modify the text to align with your suggestion @dhh1128 to be more specific. Additionally noting this solves the "how do we identify DIDCommV1 vs V2 without relying on transport" problem.

**Comment by awoie** [comment]
What is the status of this?

IMO, we must enable an approach that does not require content sniffing to identify whether the JWE/JWS/JSON is a DIDComm Message. 

For this reason, I would be in favour of requiring `cty` (or another property/header) to be set to one of the media types defined in the spec, e.g., `application/didcomm-encrypted+json`. There is no reason to introduce those media types if we don't use them to prevent content sniffing or additional context information.

I suggest two changes to the spec:
- change SHOULD have media type into MUST have media type, e.g., `application/didcomm-encrypted+json``
- MUST use the media type for the `cty` header (JWS(JWE), or property (Plaintext/JSON).

Any thoughts?

**Comment by dhh1128** [comment]
+1 for @awoie 's summary and proposed next steps.

**Comment by kdenhartog** [comment]
> 
> 
> What is the status of this?
> 
> IMO, we must enable an approach that does not require content sniffing to identify whether the JWE/JWS/JSON is a DIDComm Message.
> 
> For this reason, I would be in favour of requiring `cty` (or another property/header) to be set to one of the media types defined in the spec, e.g., `application/didcomm-encrypted+json`. There is no reason to introduce those media types if we don't use them to prevent content sniffing or additional context information.
> 
> I suggest two changes to the spec:
> 
>     * change SHOULD have media type into MUST have media type, e.g., `application/didcomm-encrypted+json`
> 
>     * MUST use the media type for the `cty` header (JWS(JWE), or property (Plaintext/JSON).
> 
> 
> Any thoughts? After reading this thread, there seem also to be consensus in our group?

+1 from me as well for summary and proposed next steps.
