### ISSUE TITLE
Align DID document service type with Aries DID Doc conventions?

### ISSUE THREAD

**Issue by domwoe** [decentralized-identity/didcomm-messaging#179]
Is the difference between the spec here and the Aries DID Document conventions on purpose or should this be aligned ?

[DIF Service type: "DIDcomm"](https://identity.foundation/didcomm-messaging/spec/#did-document-service-endpoint)
[Aries DID Doc convention service type "did-communication"](https://github.com/hyperledger/aries-rfcs/blob/master/features/0067-didcomm-diddoc-conventions/README.md#service-conventions)

**Comment by Baha-sk** [comment]
indeed they should match

**Comment by OR13** [comment]
If this "service type", is going to look different than every other type property, it should at least be registered....

https://github.com/w3c/did-spec-registries

**Comment by OR13** [comment]
strong -1 to "Aries DID Document" representations super-seeding the W3C Conventions.

**Comment by domwoe** [comment]
@troyronda @swcurran  What do you think? This could be point in time where an adjustment in Aries could be done without greater hiccups.

**Comment by TimoGlastra** [comment]
I think the types should be kept separated as they have different working.

The Aries RFCs `did-communication` includes `recipientKeys` and `routingKeys`, while this spec doesn't have a `recipientKeys` property. All keys declared in the DID Document’s `keyAgreement` section should be used as recipients when encrypting a message. Also the Aries `did-communication` includes a `priority` which I also don't see here.

Shouldn't we just interpet `did-communication` as DIDComm v1 service, and `DIDComm` as DIDComm v2 service. If you support both, you include both in your DIDDoc.

**Comment by TelegramSam** [comment]
Per previous WG discussions, this intentionally does not align with DIDComm V1 (Aries) conventions in order to tell them apart.

This will be discussed in today's WG meeting.

**Comment by OR13** [comment]
I think its a good idea to make DIDComm v1 and DIDComm v2 distinguishable... I hate to suggest date stamping but thats also an option.

It wouldn't be the end of the world if the service type were different, if it was well documented and registered.

**Comment by kdenhartog** [comment]
@TelegramSam was there an outcome to this that can be put into a PR?

**Comment by TelegramSam** [comment]
@kdenhartog I think no, but I need to chase down all the details and verify.

**Comment by mccown** [comment]
This was discussed in the DIDComm WG on 20220228.  It was decided to leave the description as is.
