### ISSUE TITLE
RFC 0023: add n-wise support

### ISSUE THREAD

**Issue by TelegramSam** [decentralized-identity/didcomm-messaging#18]
Original Issue: https://github.com/hyperledger/aries-rfcs/issues/72

**Comment by kdenhartog** [comment]
Do we need this anymore? Marking as pending close. Please update if you think it should be changed @TelegramSam

**Comment by dhh1128** [comment]
I have been cheering all the tickets that were recently marked "pending close" -- but this one made me pause. We need a way to establish a 3-way or 4-way connection in didcomm. It needs to be documented. Zero round trip may make this simpler -- but we still need to document.

This might be an application-level protocol and thus out of scope for our spec. Or it might not, given 0RT. Let's discuss in a meeting. before closing.

**Comment by TelegramSam** [comment]
The spec does not yet contain any info about multiple-party interactions.

**Comment by TelegramSam** [comment]
Discussed in WG 20211108. Messages may already be sent to mulitple parties. direct support of groups is a higher level protocol or left to future work.

**Comment by TelegramSam** [comment]
Closed per discussion in WG 20220110.
