### ISSUE TITLE
Add convention for `skid`

### ISSUE THREAD

**Issue by awoie** [decentralized-identity/didcomm-messaging#184]
To support the following flow:

- Alice wants to send (auth)encrypted message to Bob
- Alice knows Bob’s (public) DID
- Alice has a public DID
- Alice has Bob’s static public key and uses Alice’s epk and spk (matches pub key in the public DID) to encrypt message that includes a DID rotation (to a pairwise DID) to Bob
- Bob can (at least) decrypt the message without any other prior knowledge and can continue communicating with Alice using her pairwise DID, likely by including another DID rotation. 

This would assume that Alice needs to include a reference to her static public key in `skid` , otherwise Bob won’t be able to decrypt the message. If we don’t agree on a convention for `skid`, the use case above is de-facto not possible in an interoperable fashion.

`skid` MUST be a DID URI to Alice's static public key, otherwise prior knowledge of the public key is required. Certainly, this can also be a URI to a JWK but since this is DIDComm, I'm fine with limiting it to a DID URI.

**Comment by awoie** [comment]
Also note that according to the current spec:
> When a DID is rotated, the new DID is put into immediate use encrypting the message, and one additional attribute is included as a message header:

If the message is encrypted using the new DID that contains the `from_prior` DID rotation, how would a sender decrypt the message if `skid` does not have a reference to the sender key of the new DID?

**Comment by awoie** [comment]
The current ECDH-1PU draft also says that `skid` is OPTIONAL. IMO, `skid` MUST be mandatory.

**Comment by awoie** [comment]
IMO, if we assume that `skid` will be encrypted with epk and recipient key, then this convention should not be controversial. See #156

**Comment by Baha-sk** [comment]
>The current ECDH-1PU draft also says that skid is OPTIONAL. IMO, skid MUST be mandatory for DIDComm V2.
The draft is general purpose, it references `skid` the same way as a `kid` in a jwk, which is optional. But DIDComm V2 requires `skid` to identify and authenticate the sender for Authcrypt envelopes only.

>IMO, if we assume that skid will be encrypted with epk and recipient key, then this convention should not be controversial. See #156
The `skid`  is not really encrypted, it's a reference to a key, if present, then we assume the cek wrapping  for each recipient is done with an ECDH-1PU kdf style. 

If it's empty/missing, then we assume ECDH-ES kdf style is used instead (no sender key is used, ie anonymous encryption/anoncrypt).

Obviously dictating what alg to use for key wrapping should come from the recipient's `alg` header, eg:
- `"alg": "ECDH-1PU+A256KW"`
  this requires `skid` to be present in the JWE's protected headers. (sender key is needed, ie Authcrypt)
while:
- `"alg": "ECDH-ES+A256KW",`
  does not require `skid` in the protected headers. (no sender key required, ie Anoncrypt)

**Comment by awoie** [comment]
> > The current ECDH-1PU draft also says that skid is OPTIONAL. IMO, skid MUST be mandatory for DIDComm V2.
> 
> The draft is general purpose, it references `skid` the same way as a `kid` in a jwk, which is optional. But DIDComm V2
> requires `skid` to identify and authenticate the sender for Authcrypt envelopes only.

Yes, since `skid` is application-specific, DIDComm V2 can and should propose a DIDComm-specific convention that allows the recipient to resolve the public key from the `skid`.

> > IMO, if we assume that skid will be encrypted with epk and recipient key, then this convention should not be controversial. See #156
> 
> The `skid` is not really encrypted, it's a reference to a key, if present, then we assume the cek wrapping for each recipient is done with an ECDH-1PU kdf style.

Agree, it is not yet encrypted. #156 is about sending `skid` encrypted. Not sure what the current status is.

**Comment by Baha-sk** [comment]
>If it's empty/missing, then we assume ECDH-ES kdf style is used instead (no sender key is used, ie anonymous encryption/anoncrypt).
>
>Obviously dictating what alg to use for key wrapping should come from the recipient's alg header, eg:
>
>"alg": "ECDH-1PU+A256KW"
>this requires skid to be present in the JWE's protected headers. (sender key is needed, ie Authcrypt)
>while:
>"alg": "ECDH-ES+A256KW",
>does not require skid in the protected headers. (no sender key required, ie Anoncrypt)

side note: as per [Anonymous Messages](https://identity.foundation/didcomm-messaging/spec/#anonymous-messages), the sender will create a `newly minted DID doc` to be used instead. This means that DIDComm V2  has these requirements:
- `skid` protected header is effectively mandatory
- ECDH-ES family of `alg`s are not supported
