### ISSUE TITLE
How to decrypt authcrypted message with DID rotation

### ISSUE THREAD

**Issue by awoie** [decentralized-identity/didcomm-messaging#188]
The spec says:
> When a DID is rotated, the new DID is put into immediate use encrypting the message, and one additional attribute is included as a message header:

If the new DID's private key is used for authcrypt and immediately used, the recipient won't be able to decrypt the message because the recipient does not have the sender's new public key. The solution would be to include the new DID public key in the `skid`, so `skid` MUST be provided and set to the DID URI.

If privacy is a concern, we should encrypt the `skid` using sender epk and static public key of the recipient.

**Comment by Baha-sk** [comment]
>If privacy is a concern, we should encrypt the skid using sender epk and static public key of the recipient.

This text means `skid` must be a recipient header. It is not the intent of the ECDH-1PU draft to have it as a recipient header, it specifies the `skid` as a sender specific `kid` stored in the JWE's protected headers. It would be confusing to have a `skid` as a recipient header since it's a sender specific value (not tied to the recipient).

**Comment by awoie** [comment]
> > If privacy is a concern, we should encrypt the skid using sender epk and static public key of the recipient.
> 
> This text means `skid` must be a recipient header. It is not the intent of the ECDH-1PU draft to have it as a recipient header, it specifies the `skid` as a sender specific `kid` stored in the JWE's protected headers. It would be confusing to have a `skid` as a recipient header since it's a sender specific value (not tied to the recipient).

I agree that the encryption would not be aligned with the ECDH-1PU spec as the encryption is specific to the recipient. While I would be personally fine with updating the text in ECDH-1PU to support that use case, I don't know if there are other proposals that are possible with the current ECDH-1PU spec? 

E.g., you could encrypt the `skid` with a cek and put the encrypted kek in the recipient header which is encrypted using sender epk and static key of the recipient. But this might be a little convoluted :) .

**Comment by TelegramSam** [comment]
The sender's public key is encrypted to the recipient in the encryption envelope, making the message decryptable prior to evaluating the DID rotation headers. The sender's public key must be validated against the DID from and rotation headers before the message is trusted.

**Comment by TelegramSam** [comment]
I believe my above response to a clear answer to this question. Closing. Please reopen if still unclear.
