### ISSUE TITLE
Modify Action to render correctly

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/didcomm-messaging#196]
You probably want to update your GH Action for rendering to something like this one: https://github.com/decentralized-identity/presentation-exchange/blob/master/.github/workflows/render-specs.yml

**Comment by TelegramSam** [comment]
I've started looking at this.

**Comment by bumblefudge** [comment]
Oh great! I tried setting up something like for the /faq/ and gave up because I am v v v bad at GH Actions. Documentation/tutorial/examples in the spec-up repo would be great! Opening an issue now for future reference/bandwidth/DIF Grant :D

**Comment by TelegramSam** [comment]
I believe this is solved.
