### ISSUE TITLE
Do we need to Encrypt the Sender?

### ISSUE THREAD

**Issue by TelegramSam** [decentralized-identity/didcomm-messaging#197]
Encrypting the sender (either sender_pk or skid) reduces the information leaked to anybody who can inspect an encrypted message. The recipient MUST be discoverable to enable decryption. If the Sender is encrypted, then anybody inspecting an encrypted message only knows who the message is sent TO, and not FROM.

Our working group discussions brought up the fact that the encrypted message is typically only visible to the last mediator used to send a message. Other mediators will only see the FROM and TO of the outer message, or only the TO if anoncrypt is used for mediation hops.

Given this limited disclosure and the complexity of standardizing the encrypted sender, I want to verify that we need this feature.

Thoughts?

**Comment by TelegramSam** [comment]
@dhh1128 @kdenhartog @tplooker @awoie ^

**Comment by andrewwhitehead** [comment]
Just to summarize some of the negatives:
- It's not currently supported or proposed for the ECDH-1PU draft.
- It adds the overhead of an extra encryption/decryption step during envelope packing/unpacking.
- It can require two round trips to an external KMS, and potentially two authorizations (with a DID resolution in between). This leads to a desire to embed the sender key value.
- It also means that the ephemeral key and the recipient's private key are now used in two separate KDFs, potentially increasing the potential for security faults.

I'd also like to point out that the 'last mediator' would be designated by the receiver of the message, not the sender, so the sender doesn't necessarily have a way to prevent their DID from leaking in this case.

**Comment by TelegramSam** [comment]
More commentary on the observability of unencrypted senders.

> I mention observability. This only applies to the sender and recipient as they would be unencrypted. The contents of the message itself will be encrypted.

Mediation is one defense against observability. When mediation is used, The sender of the message is visible to each mediator and anybody observing the message in transit to each mediator. The recipient is only known by the last mediator. When mediation is not used, both sender and recipient are visible to anyone inspecting the message.

Another defense against observability is the use of pairwise DIDs. A Pairwise DID  is one only used in one relationship. The result of this singular correlation between sender and recipient means that no additional information is observable by knowing both the sender and recipient. (Note: For this to be true, care must be taken with the endpoint included in the pairwise DID's DID Document to avoid correlation by endpoint. This may be accomplished via unique endpoints or mediation.)

It is also possible to use anoncrypt in messages sent via mediators. This would avoid disclosure of the sender before the final message, but removes the ability to send an error message back to the sender in the event of a problem mid-mediation. 

The combination of Mediaton and Pairwise DIDs present a few combinations with effects upon observability.

**Unmediated and Non-pairwise**: Both sender and receiver are observable, and DIDs are correlated with other relationships.

**Unmediated and Pairwise**: Both sender and receiver are observable, but DIDs are uncorrelated with other relationships.

**Mediated and Non-pairwise**: Only sender is observable till final mediator, where both sender and receiver are observable. The final mediator can correlate both DIDs with other relationships. 

**Mediated and Pairwise**: Only sender is observable till final mediator, where both sender and receiver are observable. The final mediaor is unable to correlate both DIDs with other relationships.

Use of Pairwise DIDs may be employed by either or both parties. I've not enumerated that precisely for the sake of brevity.

Depending on the choices made, the problem of observability can be quite small. I do lament the complexity of this answer against the simplicity of  "sender is unobservable'.

**Comment by andrewwhitehead** [comment]
It occurs to me that when there is a pairwise relationship (in particular, when the recipient has created a single-use DID for this relationship), the sender is always known and their key can be determined based solely on the `skid`. I think the only exceptions here would be in the case of pairwise key rotation, and in an initial 'connection request' message before the relationship is established. Maybe we can take advantage of that?

**Comment by andrewwhitehead** [comment]
Given the precedent established for signed messages, where a JWS envelope is wrapped in a JWE envelope, I think it's also possible to support double-encryption when hiding the sender identity is essential. It would simply mean wrapping an authenticated ECDH-1PU envelope in an anonymous ECDH-ES envelope.

**Comment by awoie** [comment]
We will need this feature but I'm not a cryptographer, so I cannot speak to the issue of using `epk` in two KDFs. Using another ECDH-ES might be really not great for UX (in our case, since we would need two JSON RPC + consent calls in all cases). Another option (would not solve our UX issue) would be including the ECDH-ES in the `skid` directly which might be smaller in size.

**Comment by awoie** [comment]
@TelegramSam I guess we can close this issue?

**Comment by awoie** [comment]
Closing this issue since discussion happens in #219
