### ISSUE TITLE
what does this statement mean?

### ISSUE THREAD

**Issue by brianorwhatever** [decentralized-identity/didcomm-messaging#203]
| For digital signatures the following algorithms MUST be verifiable

**Comment by kdenhartog** [comment]
Sounds like something I'd be to blame for it. Can you link to where it's at for greater context?

**Comment by brianorwhatever** [comment]
https://identity.foundation/didcomm-messaging/spec/#algorithms

I was guessing it meant an implementation must be able to verify all of those algs?

**Comment by kdenhartog** [comment]
Ahh good catch. Looks a bit redundant based on the sentence that follows it. I think we're good to just strike that sentence. @brianorwhatever Can you take this PR?

**Comment by brianorwhatever** [comment]
I think it's saying that you have to be able to verify all 3 however you only have to be able to sign using 1 of the 3. I have created #230 to clarify this. Let me know what you think
