### ISSUE TITLE
should skid be in the auth section of the DID Doc?

### ISSUE THREAD

**Issue by awoie** [decentralized-identity/didcomm-messaging#204]
Since authcrypt is a form of sender authentication, should we assume that the corresponding key is also listed in the authentication section of the sender's DID Doc (in addition to the keyAgreement section)?

**Comment by Baha-sk** [comment]
I believe it will add redundancy in the DID Doc

**Comment by kdenhartog** [comment]
For the key used to perform ECDH operations, I think staying with `keyAgreement` would remain most consistent across the DID ecosystem. Trying to make sure that a key is used in both is likely going to add more complexity than any perceived benefits we'd gain from it. I'd think it's more practical to just leave it with one for now.

**Comment by awoie** [comment]
Ok, I agree. I'm fine with closing this issue.

**Comment by awoie** [comment]
Closing issue -- no spec changes needed.
