### ISSUE TITLE
set skid/combined recipients kid values in APU/APV respectively as protected headers

### ISSUE THREAD

**Issue by Baha-sk** [decentralized-identity/didcomm-messaging#205]
The 1PU draft4 [example B](https://github.com/NeilMadden/jose-ecdh-1pu/blob/master/draft-madden-jose-ecdh-1pu-04/draft-madden-jose-ecdh-1pu-04.txt#L794) has the recipient headers stored in the ProtectedHeaders, particularly the APU and APV fields representing the sender (producer) and recipients (combined receivers), in our Aries RFC 334, we proposed to add the recipients’ kids in the AAD section (see authcrypt example [here](https://github.com/hyperledger/aries-rfcs/tree/master/features/0334-jwe-envelope#authcrypt-using-ecdh-1pu-key-wrapping-mode)).

I propose we set the the sender kid in APU (same value as skid) and the list of recipient’s kids in APV since draft4 is using the common protectedHeaders for these. The recipient kid remains under the recipients headers as per the example, only the other headers are now common for all recipients since we use a common epk for all recipients and the content encryption is done prior to key wrapping (since the encryption tag is used in the key wrapping process). This means we don’t need to set the list of recipients in AAD anymore.

**Comment by kdenhartog** [comment]
+1 to this suggestion as discussed on DIF slack channel.
