### ISSUE TITLE
Should we flip to CBOR?

### ISSUE THREAD

**Issue by dhh1128** [decentralized-identity/didcomm-messaging#207]
Before we ever began the DIDComm v2 effort, I had a conversation with @tplooker about the advisability of basing DIDComm on something binary instead of on JSON. I told him then that I thought we could go full-on binary if we did it from the inception of the v2 effort, but that changing to binary once we were well underway would be too painful. So my advice then was to either propose CBOR immediately, or leave it alone.

(History: the *very first* ancestor of modern DIDComm, called A2A in the what was then the Hyperledger Indy community, was implemented with binary serialization using MsgPack. We had an IIW meeting soon after that where we talked about message formats, and I came to a session called by Sam C where the question of these formats was debated a bit. I was passionately in favor of binary over JSON because we already had something working, and I didn't want to have to change it. But I got voted down, and we became very JSON-oriented for all of DIDComm v1 -- and then, by inheritance, DIDComm v2.)

I've been content to let this decision ride, but today I had an interesting conversation with some advocates of KERI that left me feeling really discouraged about the semantic and architectural overhead we're incurring, constantly, by being JSON-centric. (This isn't a comment about KERI, particularly -- and the KERI proponents I was talking to weren't dissing JSON, they were defending it. But their defense left me squirming. The impedance mismatch between JSON and communication features rears its head periodically in lots of contexts. It just happened to be a KERI conversation where my discomfort came to a head today.)

Now, I know that it is very late in the DIDcomm v2 lifecycle to be asking this question, and that I am contradicting my own earlier advice to even ask the question again. But what I'm proposing to do in this issue is to document for posterity (in this issue's comment stream) why we chose to base DIDComm v2 on JSON instead of CBOR. Then, if we are content with the outcome, I'll be content as well -- and we'll lay this issue to rest forever, with a citable public conversation about why. If, on the other hand, others begin to squirm in the same way I did, we could debate whether we want to change our minds.

**Comment by OR13** [comment]
you should use CBOR-LD :) 

bi-directional transformations between JSON and CBOR, that preserve semantics.

You can build specific encoders for base64url / JWE / other JSON fields that are taking up more space than they need to.

Vanilla CBOR really sucks to use... and so does COSE.

There are also registry issues with vanilla CBOR, which can be extremely painful / delay your ability to make progress.

You would end up having 2 DIDComm formats if you went down that road, with the JSON one being the most popular.

Better to just upgrade the JSON to compact binary, by adding an `@context`... instead of reinventing all those wheels.

**Comment by dhh1128** [comment]
To start the discussion, ere are some relevant pros and cons of binary vs. JSON, as I understand them. Hopefully others will add to my list, or correct my thinking where I go astray.

### Signatures

Signing JSON repeatedly creates headaches for us. We have generally avoided the worst of this issue by saying that we will sign a byte stream, and that the byte stream will always show up as base64-encoded data in our messages. But we continue to have problems where we want to embed something in a message that is understood as something more flexible than a byte stream -- for example, a verifiable credential that is serialized as JSON and then undergoes a canonicalization process before being signed. The KERI conversation that triggered me today involved a proposal to externalize the signature for a VC (put the VC inside a larger JSON data structure, with the signature *outside* the VC part). The problem with this is that people will look at the inner, signed VC part and not know how it is canonicalized. And then there will be documents that describe the canonicalization -- but there will be specs written that show sample JSON in prettified rather than canonicalized form, so what we show in specs and what we actually sign will remain distinct with mostly tribal knowledge to plug the gap. I feel like I have had a dozen conversations around this problem over the course of the past two years. I *really*, *really* do not want to incur a dependency on full-blown JSON canonicalization, or on JSON-LD, for ordinary DIDComm. If we say that a DIDComm message isn't JSON in the first place, this problem largely vanishes, since we are always dealing in byte streams instead.

### Bloat

We agreed to ignore the 33% bloat of base64-encoding attachments. But we wouldn't have any bloat at all if we just used a format that was capable of transferring binary directly. This gives us 33% more we can fit in QR codes, etc. A lot of the work Tobias demonstrated, on shrinking VCs to fit on paper, may apply to DIDComm as well...

### JOSE

The strongest argument in favor of JSON, IMO, is that it gives us all the JOSE mechanisms out of the box. But we are learning that "out of the box" isn't nearly as compelling as it sounds. We have to go retrofit ECDH-1PU support onto JOSE libraries, and maybe tweak other stuff as well -- and we have to decide exactly what we're putting in `cty` headers, etc. COSE is not super mature, but maybe that's okay, because the mature JOSE stuff isn't feeling very "out of the box" to me right now, anyway?

### Affinity for DIDComm Streaming or other?

If we wanted DID-based security for a streaming cousin to DIDComm messaging, I suspect binary would look pretty compelling.

**Comment by dhh1128** [comment]
(My second comment and the comment from @OR13 crossed in the ether.)

Regarding CBOR-LD: DIDComm has taken the position that the possibilities of linked data are interesting, but we are unwilling to *require* implementations to adopt them, because most message families we imagine don't need them. So we made linked data a per-protocol decision rather than baking it into the foundation. I believe this was the right decision, and don't want to revisit it -- so I suggest that we constrain this discussion to binary-vs-JSON and assume that linked data remains a per-protocol choice in either case.

If we want to revisit the linked data question as well, let's use a different issue for it.

**Comment by dhh1128** [comment]
@OR13 , I want to understand more deeply some of your earlier comments.

>You can build specific encoders for base64url / JWE / other JSON fields that are taking up more space than they need to.

Do you mean going into the serialization libraries for a given programming language (e.g., Jackson on the JVM, serde on Rust) and overriding how specific fields are handled? If so, that feels yucky. Do you agree?

>Vanilla CBOR really sucks to use...

This is the comment that intrigues me the most. I have only used CBOR in two programming languages -- python and Kotlin -- but it was very easy and clean. Can you say more about your unhappy experience?

>and so does COSE.

I have no experience with COSE at all, so if it's yucky, that's important to know. Do others share this opinion?

>There are also registry issues with vanilla CBOR, which can be extremely painful / delay your ability to make progress.

Why do we need a registry at all? What are we registering? Are you talking about the registry for the semantic layer that linked data wants?

>You would end up having 2 DIDComm formats if you went down that road, with the JSON one being the most popular.

To be clear, I would be violently opposed to having an either/or strategy. Either DIDComm v2 is JSON, or it's binary (e.g., CBOR). Under no circumstances would I vote for both.

**Comment by troyronda** [comment]
> we could debate whether we want to change our minds.

I do not want to change to CBOR in this version. We already have JSON/JOSE implementations (along with JSON-LD/LD Proof). Going to JWM (but still JSON/JOSE) is a more consumable activity than asking for change at another layer (COSE and everything that goes with it).

**Comment by troyronda** [comment]
> we could debate whether we want to change our minds.

I do not want to change to CBOR. We already have JSON/JOSE implementations for DIDComm (alongside JSON-LD/LD Proof for VCs). Going to JWM (but still JSON/JOSE) is a more consumable activity than asking for change at another layer (CBOR, COSE and everything that goes with it).

**Comment by kdenhartog** [comment]
I regard this as more of a documentation issue so that we have our rationale for why we ended up not going for CBOR.

FWIW, my take on this is I think CBOR would be valuable, but it's too late in the game to make this switch at this point. We've done all the railwork to set ourselves up for optimization when the interest to make this happen is. I think we're going to need to get something working first and then when we're trying to scale to massive throughputs worth of messages this will be more valuable (and I highly suspect mediator services will be the one driving this effort in the future).

**Comment by dhh1128** [comment]
Okay, I'm happy viewing this more as a documentation issue (the ship has already sailed; we just need to explain why).
