### ISSUE TITLE
Questions and comments re routing/forward

### ISSUE THREAD

**Issue by awoie** [decentralized-identity/didcomm-messaging#210]
Imagine you have the following service in the services section of Bob's DID Doc and this DID Doc was exchanged OOB with Alice:

```
{
    "id": "did:example:bob#didcomm-1",
    "type": "DIDCommMessaging",
    "serviceEndpoint": "did:example:somemediator",
    "routingKeys": ["did:example:anothermediator#somekey"]
}
```
Now, Alice wants to send Bob a message.

Alice would do the following:
- Create the message and pack the message to Bob's `keyAgreement` keys from Bob's DID Doc.
- Dereference `did:example:anothermediator#somekey` and find one particular `keyAgreement` key.
- Create a forward `message A` that wraps the packed message to anothermediator's somekey (JWE with one recipient).
- Resolve `did:example:somemediator` and get somemediator's `keyAgreement` keys as well as somemediator's serviceEndpoint.
- Create another forward `message B` that wraps `message A` to all `keyAgreement` keys of somemediator (JWE with multiple recipients).

Now...

`next` is currently defined as a DID

I assume `message B` looks something like:

```
{
    "type": "https://didcomm.org/routing/2.0/forward",
    "to": ["did:example:somemediator"],
    "expires_time": 1516385931,
    "body":{
        "next": "did:example:anothermediator",
        "payloads~attach": [
            // JWE forward message A
        ]
    }
}
```

And `message A` looks something like:
```
{
    "type": "https://didcomm.org/routing/2.0/forward",
    "to": ["did:example:anothermediator"],
    "expires_time": 1516385931,
    "body":{
        "next": "did:example:bob",
        "payloads~attach": [
            // JWE message from Alice to Bob
        ]
    }
}
```

A couple of questions:
1. The current spec says, don't use `to` for `forward` messages. Is this still the case since the `forward` message examples show the `to` property? A recipient (also mediator) will be able check the `kid` whether it is the intended recipient.
2. Which service endpoint will be used for `message A`? Is Alice expected to get the service endpoint from the DID resolution result of `did:example:anothermediator`? If this is the case, we need normative language for that in the spec.
3. When would you actually have multiple array entries in the `to` property? If Bob has multiple `keyAgreement` keys, would you add the DID URLs of each of those to the `to` property of the message that is intended for Bob? I would not assume so, right (since I expect the recipient section would do that job) ?
4. We should probably add some language that authcrypt for forward messages is discouraged since it would defeat its purpose?

**Updated** to fix some issues in the descripton!

**Comment by awoie** [comment]
5. Another question...

Given Bob has the following DID Doc:

```
{
    "id": "did:example:123456789abcdefghi#didcomm-1",
    "type": "DIDCommMessaging",
    "serviceEndpoint": "http://example.com/path",
    "accept": [
       "didcomm/v2",
       "didcomm/aip2;env=rfc587"
     ],
     "routingKeys": ["did:example:somemediator#somekey"]
}
```

What if `did:example:somemediator` defines its own serviceEndpoint which is different from `http://example.com/path`. How would you assume that the forward message will be received by `did:example:somemediator` since only `did:example:somemediator` can decrypt the forward message?

**Comment by awoie** [comment]
Pls refer to 1, 2, 3, 4, 5 when replying to this thread.

**Comment by kdenhartog** [comment]
Labelling this as a V2 for now, until we can separate out what's needed to be define in V2 versus what can be deferred into a routing extension document.

**Comment by awoie** [comment]
Resolution from DIDComm WG meeting, 23rd August:
- DID Docs (Bob's) with URI as serviceEndpoint + routing keys of mediator is intentionally supported (for proxy use cases). Implementers need to ensure, they can decrypt the messages.
- PR needed: Add informative language on `to` property. Value is just to provide more context for Bob. Bob cannot verify that other entities (e.g., Carol) received the message. Alice can add values to `to` property without enforcing verification of those by Bob.

---
IMO, it might also makes sense to add more DID Doc examples for routing + use cases.
