### ISSUE TITLE
Need more details about protected `skid`

### ISSUE THREAD

**Issue by dhh1128** [decentralized-identity/didcomm-messaging#219]
A developer wanting to implement the spec read this section:

>https://identity.foundation/didcomm-messaging/spec/#protecting-the-skid-header

His comment was that there is not enough detail to implement this mechanism. I agree with him. I think we need an example of what is meant by this sentence:

>MAY include an encrypted_skid header with a value based on the encryption of skid using ECDH-ES Z computation of the epk and the recipient’s key as the encryption key.

**Comment by dhh1128** [comment]
tagging @vimmerru

**Comment by awoie** [comment]
We agreed to revise this section in a separate PR: https://github.com/decentralized-identity/didcomm-messaging/pull/185#issuecomment-860928028 . AFAIK, the decision was to not encrypt the `skid` and using `encrypted_skid`. We would rather add non-normative language how protection can be achieved by other means, e.g., pairwise-sender-DIDs, or anoncrypt(authcrypt(msg)).

**Comment by ashcherbakov** [comment]
@kdenhartog it looks like this issue should have `PR Needed` label, as the current spec doesn't provide full or up-to-date information related to `skid`. Do you agree?

**Comment by kdenhartog** [comment]
Looks like I didn't think about this enough when triaging. Thanks for the suggestion updated that.

**Comment by vimmerru** [comment]
We discussed it internally with @ashcherbakov and got some recommendations you can consider:

1. Proposed way to hide sender (use `anoncrypt(authcrypt())`) doesn't look optimal. It will require `n` additional ECDH operations and key wrappings, additional content encryption and size of the message will  growth significantly. It obviously complicates protocol (forces message layering) and opens possible misusage ways.
1. JWE/ECDH-1PU specifications doesn't specify how content of skid header should look like. It should only allow recipient to determine the key of sender. So i think we don't need dedicated `protected_skid` header and can just use `skid` header to complain JWE/ECDH-1PU.
1. For pairwise or even n-wise communication when recipient party knows in advance the sender DID (or possible sender DIDs) we can use `H(KeyURI, IVkw, Tagkw)` as SKID. Recipient can iterate over sender DIDDoc/DIDDocs and find a key that corresponds to hash. 
1. For open communication KID can be anoncrypted JWE that uses same recipient keys. Potentially we can consider re-usage of ephemeral keys or other secrets used for ECDH-1PU to reduce amount of crypto operations, but it require more time for analysis.


Tagging @ashcherbakov @dhh1128 who may have an interest.

**Comment by TelegramSam** [comment]
>For pairwise or even n-wise communication when recipient party knows in advance the sender DID (or possible sender DIDs) we can use H(KeyURI, IVcek, TAGcek) as SKID. Recipient can iterate over sender DIDDoc/DIDDocs and find a key that corresponds to hash.
This becomes the difficulty - current design allows for authcrypted messages to be sent to a recipient from a new sender, and in situations of did rotation, where the provenance of the rotation is contained within the message.

To make the encrypted (or obfuscated) sender to work, it must work with previously unknown senders.

Your point about skid is interesting though - we can allow both DIDs and encrypted DIDs in the same skid field, so long as we can easily differentiate between them.

**Comment by TelegramSam** [comment]
Related: #197

**Comment by vimmerru** [comment]
@TelegramSam 

> This becomes the difficulty - current design allows for authcrypted messages to be sent to a recipient from a new sender, and in situations of did rotation, where the provenance of the rotation is contained within the message.

I don't see a problem here as "unknown" sender and "did rotation" are quite rarely cases and for such cases we can continue use anoncrypt wrapper, but for other 99.9999% of messages we can avoid re-encryption and additional ECDH that will save of lot of electricity.

**Comment by dhh1128** [comment]
DID rotation is going to be common; it is how we change from using a public DID to using a pairwise DID.

**Comment by vimmerru** [comment]
> DID rotation is going to be common;

I don't say it is "not common". I just say it is rarely case from amount of messages point of view. When sender can't be determined based on recipient DID the current proposal is use additional `anoncrypt`container, but we don't need forcing it when sender is known to recipient.

> it is how we change from using a public DID to using a pairwise DID.

Do we have any document about this?

**Comment by AnomalRoil** [comment]
Just to be sure we all understand the same thing:
> MAY include an encrypted_skid header with a value based on the encryption of skid using ECDH-ES Z computation of the epk and the recipient’s key as the encryption key.

My understanding is that it means that when Alice is doing `authcryption` for Bob, she will also use the ephemeral key she generated for the ECDH-1PU process to perform a "regular" ECDH-ES direct key agreement between that ephemeral key and Bob's static key and use the resulting key to encrypt her skid/apu fields, in order to hide the provenance. 

Bob upon reception can see there's an encrypted skid, and use the `epk` field to decrypt the encrypted_skid by using his private key and the `epk` to derive the key encrypting the `skid`, and then use that decrypted `skid` to perform authcrypt decryption of the ciphertext as usual.

I'm failing to see how this is causing message layering.

Also I agree with your point 2., the `skid` field can contain structured data that allows easily further processing.

**Comment by ashcherbakov** [comment]
> My understanding is that it means that when Alice is doing authcryption for Bob, she will also use the ephemeral key she generated for the ECDH-1PU process to perform a "regular" ECDH-ES direct key agreement between that ephemeral key and Bob's static key and use the resulting key to encrypt her skid/apu fields, in order to hide the provenance.

Yes, it can be done like this, but the current proposal of DIDComm community is just to wrap the authcrypt into another anoncrypt (causing a new EPK and two layers of encryption).
See https://identity.foundation/didcomm-messaging/spec/#protecting-the-sender-identity
> A layer of anonymous encryption (employing ECDH-ES) may be applied around an authenticated encryption envelope (employing ECDH-1PU), obscuring the sender’s identity for all but the recipient of the inner envelope. In the case of a message forwarded via mediators, anonymous encryption is automatic

So, the goal of this ticket is to either conform that what's written in the spec is correct, or design an alternative (and more efficient) approach and reflect it in the spec explicitly.

**Comment by awoie** [comment]
We had a long conversation on why we don't want to use an encrypted `skid`. So, IMO, what is in the spec is correct. If you want to protect the sender, use anoncrypt to wrap the authcrypted envelope, or use pairwise DIDs from the start.

**Comment by vimmerru** [comment]
@awoie 

> or use pairwise DIDs from the start.

I completely support this, but current spec doesn't allow `pairwise DIDs` to be used. DIDs may contain multiple keys and we need to define how to handle this in compatible way.

**Comment by AnomalRoil** [comment]
> but current spec doesn't allow `pairwise DIDs` to be used

Do you have an exact reference for that? I didn't understand the spec in that way.

**Comment by dhh1128** [comment]
I am also curious to understand why pairwise DIDs cannot be used. Please clarify, @vimmerru .

**Comment by awoie** [comment]
Me too, I don't see why pairwise DIDs cannot be used. IMO, that is completely out-of-scope. Nobody prevents me from creating a new DID before I send a message.

**Comment by awoie** [comment]
> As i understand you are thinking that If there is pairwise or n-wise DID there is no problem to disclose `sender id` and allow correlation of all messages as become to specific group by any mediator, but I think it is _critical privacy_ problem that will be show stopper for the most of use cases.

@vimmerru I do understand your point and that is why I personally prefer anoncrypt(authcrypt(msg)) for cases where the recipient is not trusting the mediator.

_Note, IMHO, if one used pairwise DIDs or/and rotated to a new DID, you would need to put the new DID URL in the `skid`, otherwise the recipient won't be able to decrypt the message. This is because the current spec says that the new DID should be used immediately for encryption._

**Comment by dhh1128** [comment]
Okay, I now understand the perspectives a little better after that clarification, @vimmerru . Thank you.

What was confusing me was that you used the word "pairwise" -- when the correlation issue that we discussed in detail was about an n-wise use case. The diagram I drew to understand your concern was with 3 parties, not 2. Here's that diagram, for others that are curious:

![privacy concern](https://i.ibb.co/gVw8SG2/Multi-recipient-Encryption-in-DIDComm.png)

You convinced me that in a 3-way group, we have a critical privacy problem, as the diagram notes. But I had not connected that conversation about 3-way with this conversation about 2-way. (Perhaps I was just being slow to realize the implications of what you were saying.)

Now that I ponder it more closely, I see that the problem with privacy in pairwise is almost as bad -- the mediator immediately before the final recipient learns the ID of the sender and the ID of the recipient, 100% of the time, unless the anoncrypt(authcrypt(msg)) construct is used. In the case where the mediator in question is Bob's cloud agent and its job is to deliver to Bob's edge agent, this is not a problem (Bob will probably trust his cloud agent to learn who the sender is, and may even want that to happen so his cloud agent can filter spam or apply other policies). But in the case where the mediator in question is outside Bob's sovereign domain (e.g., is an agency that routes mail for Bob), this is clearly undesirable.

Do you have a concrete counter-proposal to the anoncrypt(authcrypt(msg)) mechanism? (We chose this mechanism not because we loved it, but because it was easy to explain and implement, and required no extensions to JWE or EDCH-1PU. We all agreed that it was inefficient. A better solution would be great, if you know one.)

**Comment by vimmerru** [comment]
> You convinced me that in a 3-way group, we have a critical privacy problem, as the diagram notes. But I had not connected that conversation about 3-way with this conversation about 2-way. (Perhaps I was just being slow to realize the implications of what you were saying.)

I think 2-way case when Eva from millions of messages can easily match every message to specific group/thread/conversation is also very big privacy problem.

**Comment by dhh1128** [comment]
I asked you for a counter-proposal, @vimmerru . Looking back through the comment stream, perhaps you felt that this was one:

>For pairwise or even n-wise communication when recipient party knows in advance the sender DID (or possible sender DIDs) we can use H(KeyURI, IVcek, TAGcek) as SKID. Recipient can iterate over sender DIDDoc/DIDDocs and find a key that corresponds to hash.

I didn't consider this a valid counterproposal because I thought the chances that the recipient will know the sender DIDs would be low. But maybe I am wrong. Could the recipient use their own pairwise DID to deduce the DID of the sender (e.g., "I, Alice, am looking at a message sent to A.did in the Alice:Bob relationship. Therefore the sender must be B.did@A:B.")?

**Comment by vimmerru** [comment]
> Do you have a concrete counter-proposal to the anoncrypt(authcrypt(msg)) mechanism? (We chose this mechanism not because we loved it, but because it was easy to explain and implement, and required no extensions to JWE or EDCH-1PU. We all agreed that it was inefficient. A better solution would be great, if you know one.)

Yes, you can find it few messages above https://github.com/decentralized-identity/didcomm-messaging/issues/219#issuecomment-889019607

**Comment by vimmerru** [comment]
> I didn't consider this a valid counterproposal because I thought the chances that the recipient will know the sender DIDs would be low. But maybe I am wrong. Could the recipient use their own pairwise DID to deduce the DID of the sender (e.g., "I, Alice, am looking at a message sent to A.did in the Alice:Bob relationship. Therefore the sender must be B.did@A:B.")?

In my proposal we have 4 points. Not only this number 3. Point number 4 describes what we should do if DID of sender is unknown. I think it is mostly the same as `anoncrypt` wrapper except possible optimisation on ECDH amount.

I am not aware about any `pairwise` related cases when Bob doesn't know Alice's DID after pairwise is established except DID-rotation for specific DID methods like `did:key`, but as i said they can be handled by anoncrypt wrapper.

**Comment by dhh1128** [comment]
>I am not aware about any pairwise related cases when Bob doesn't know Alice's DID after pairwise is established except DID-rotation for specific DID methods like did:key, but as i said they can be handled by anoncrypt wrapper.

There is a crucial disconnect here that has to do with DIDComm v2's concept of zero-round trip. In DIDComm v1, the idea was to establish a connection and then run protocols over that connection. Connection establishment was a discrete phase in the lifecycle. In DIDComm v2, the idea is to eliminate the need to set up a connection before you can do "real work." Rather, you start doing "real work" *before* you set up a connection, and do a DID rotation inline with your messages, by using some message headers. As an example, an institution who does not have a standing relationship with Bob sends Bob an invitation to receive a credential (NOT an invitation to connect). This invitation is sent with the institution's public DID. Bob then responds with a private DID that he has allocated for that conversation. The institution then responds using an entirely new DID, still encrypting for Bob's pairwise DID, and proving that the DID rotation is authorized by a key from the old DID. This has 2 implications:

1. Many DIDs will be short-lived -- more than we imagined in v1 -- because we won't even create them until a workflow is underway.
2. Rotations will be relatively common. I agree that they won't happen on a high % of the messages. But it will probably be several orders of magnitude more than your estimate of 0.0001%.

The other thing to say is that the concern about Alice being correlated by Eva feels like a corner case, because very often, Alice will use her cloud agent as a way mediator that pick up messages from the agency and forward them to her mobile device. In such a case, it is Alice's own cloud agent, NOT the agency's mediator that sits in front of it, that discovers the `skid` of the sender. 

None of this invalidates your concern, @vimmerru . I'm just trying to explain why others on this thread have been prioritizing other things.

**Comment by dhh1128** [comment]
>In my proposal we have 4 points. Not only this number 3.

Okay, let me engage on each of them, because I think we are making progress.

>1. Proposed way to hide sender (use anoncrypt(authcrypt())) doesn't look optimal. It will require n additional ECDH operations and key wrappings, additional content encryption and size of the message will growth significantly.

I thought it only required 1 additional key wrapping, for the proximate mediator, no matter how complex the route and no matter how many recipients? We don't have to do this for any of the other mediators in the delivery route, since they should already be getting an anonycrypted `forward` message anyway -- correct? If yes, then I think the inefficiency argument is not very compelling, but I think your other argument, about opening ways for misuse, is stronger.

>2. JWE/ECDH-1PU specifications doesn't specify how content of skid header should look like. It should only allow recipient to determine the key of sender. So i think we don't need dedicated protected_skid header and can just use skid header to complain JWE/ECDH-1PU.

Okay, conceded. Sam also agreed with this point, I think.

>3. For pairwise or even n-wise communication when recipient party knows in advance the sender DID (or possible sender DIDs) we can use H(KeyURI, IVcek, TAGcek) as SKID. Recipient can iterate over sender DIDDoc/DIDDocs and find a key that corresponds to hash.

Agreed that this is possible and not very hard. It does make the SKID a bit weird, but maybe that's okay.

>4. For open communication KID can be anoncrypted JWE that uses same recipient keys. Potentially we can consider re-usage of ephemeral keys or other secrets used for ECDH-1PU to reduce amount of crypto operations, but it require more time for analysis.

This sounds like a bad idea from a security point of view. And I'm not sure I fully understand how/why we would make the value of KID into a full-blown JWE.

So, summarizing, I think I could agree with your proposal if you had a more completely thought-out point 4, and maybe if I agreed with your point 1 more strongly. (Maybe I agree with your point 1 enough, as-is.)

**Comment by vimmerru** [comment]
> I thought it only required 1 additional key wrapping, for the proximate mediator, no matter how complex the route and no matter how many recipients? We don't have to do this for any of the other mediators in the delivery route, since they should already be getting an anonycrypted forward message anyway -- correct? If yes, then I think the inefficiency argument is not very compelling, but I think your other argument, about opening ways for misuse, is stronger.

Let assume Alice want to send message to Bob that has 3 edge devices. To hide sender Alice will need:

- Generate 3 ephemeral keys
- Perform 3 ECDH for ECDH-EC (quite expensive)
- Perform 3 keys wrappings
- Perform 1 content encryption

**Comment by awoie** [comment]
`skid` is a protected header, so you'd need to include a JWE in the `skid` to encrypt the `skid` to multiple recipients. Further, there were some concerns of using the same epk in multiple KDF functions. Some people also mentioned the layering as an issue, so you'd need to decrypt the `skid` first before you could pass the correct sender public key to the 1pu decrypt function 

In #185, #191 and #197 , you can find a lot of discussions around protecting skid.

**Comment by ashcherbakov** [comment]
> I thought it only required 1 additional key wrapping, for the proximate mediator, no matter how complex the route and no matter how many recipients? We don't have to do this for any of the other mediators in the delivery route, since they should already be getting an anonycrypted forward message anyway -- correct? If yes, then I think the inefficiency argument is not very compelling, but I think your other argument, about opening ways for misuse, is stronger.

@dhh1128 
We want to hide the sender ID (Alice's ID) from the final Bob's mediator. So, anoncrypt as part of Forward doesn't help. Instead, we need to
1) Perform authcrypt for every Bob'b key where plaintext is the payload
2) Perform anoncrypt for every Bob's key again where the authcrypted message is the payload. Without this step we can not guarantee that only Bob can read the sender ID. And as we don't know what Bob's device will perform it, we have to do it for every Bob's key as in original authcrypt.

> This sounds like a bad idea from a security point of view. And I'm not sure I fully understand how/why we would make the value of KID into a full-blown JWE.

Can you please explain it in more details? We also don't have confidence that it will be 100% secure, but I think the idea similar to our Item 4 has also been raised by @AnomalRoil.

**Comment by vimmerru** [comment]
> skid is a protected header, so you'd need to include something like a JWE in the skid to encrypt the skid to multiple recipients.

@awoie  Protected header means it is included to MAC, not encrypted.

**Comment by awoie** [comment]
> > skid is a protected header, so you'd need to include something like a JWE in the skid to encrypt the skid to multiple recipients.
> 
> @awoie Protected header means it is included to MAC, not encrypted.

Yep, but as far as I know, this also means, it won't be included in the per recipient headers. Not sure if this has an implication on your proposal but I guess it might have.

**Comment by awoie** [comment]
I guess it would be good if @Baha-sk could take a look at the proposal.

**Comment by Baha-sk** [comment]
> > In my proposal we have 4 points. Not only this number 3.
> 
> Okay, let me engage on each of them, because I think we are making progress.
> 
> > 1. Proposed way to hide sender (use anoncrypt(authcrypt())) doesn't look optimal. It will require n additional ECDH operations and key wrappings, additional content encryption and size of the message will growth significantly.
> 
> I thought it only required 1 additional key wrapping, for the proximate mediator, no matter how complex the route and no matter how many recipients? We don't have to do this for any of the other mediators in the delivery route, since they should already be getting an anonycrypted `forward` message anyway -- correct? If yes, then I think the inefficiency argument is not very compelling, but I think your other argument, about opening ways for misuse, is stronger.
> 

Yes `Anoncrypt()` requires ECDH-ES+keywrap for each recipient key then Authcrypt() requires ECDH-1PU+keywrap for each recipient key again.  I'm not sure why we're saying the message will grow significantly, it's double the protected headers and double recipients at most:
1. ECDH-1PU + recipients key wrapping + msg encryption
2. ECDH-ES + recipients key wrapping + msg encryption where msg is the output of step one above.

> > 1. JWE/ECDH-1PU specifications doesn't specify how content of skid header should look like. It should only allow recipient to determine the key of sender. So i think we don't need dedicated protected_skid header and can just use skid header to complain JWE/ECDH-1PU.
> 
> Okay, conceded. Sam also agreed with this point, I think.
> 

I think we all agree on this.

> > 1. For pairwise or even n-wise communication when recipient party knows in advance the sender DID (or possible sender DIDs) we can use H(KeyURI, IVcek, TAGcek) as SKID. Recipient can iterate over sender DIDDoc/DIDDocs and find a key that corresponds to hash.
> 
> Agreed that this is possible and not very hard. It does make the SKID a bit weird, but maybe that's okay.
> 

My main concern is about `Recipient can iterate over sender DIDDoc/DIDDocs`: How does the recipient know the sender docs if she/he doesn't know who the sender is? Remember, unpacking a message is the first entry point in DIDComm, it is not aware of any DIDs, did connections/records or any key ID except for those found in the JWE's `skid` protected header and recipients `kid` header. 

This proposal does not sound reasonable to me unless we come up with a senders DIDs local registry for which an agent can lookup DIDdocs (similar to VDR). But even if we do have such registry, calling many times `H()` can be quiet expensive as it must be computed for as many incompatible senders in the registry prior to getting the right one (imagine a registry of 1 million DIDs and the right sender is the last one, this means 1M x `H()` calls which will cost a huge performance hit). 

> > 1. For open communication KID can be anoncrypted JWE that uses same recipient keys. Potentially we can consider re-usage of ephemeral keys or other secrets used for ECDH-1PU to reduce amount of crypto operations, but it require more time for analysis.
> 
> This sounds like a bad idea from a security point of view. And I'm not sure I fully understand how/why we would make the value of KID into a full-blown JWE.
> 

Reuse of `epk`/`cek` (or `iv`/`tag`) is not recommended and just opens the door to security holes in the protocol. I don't agree with proposal.

> So, summarizing, I think I could agree with your proposal if you had a more completely thought-out point 4, and maybe if I agreed with your point 1 more strongly. (Maybe I agree with your point 1 enough, as-is.)

To conclude, imho, Anoncrypt(Authcrypt()) is the best way to secure `skid`.

**Comment by vimmerru** [comment]
> My main concern is about Recipient can iterate over sender DIDDoc/DIDDocs: How does the recipient know the sender docs if she/he doesn't know who the sender is? Remember, unpacking a message is the first entry point in DIDComm, it is not aware of any DIDs, did connections/records or any key ID except for those found in the JWE's skid protected header and recipients kid header.

Recipient can determine sender by recipient DID in advance in the most of cases just because `pairwise connection` is the foundation of trust. Near any implementation of SSI i saw stores pairs of DIDs. If sender is unknown to you there is no big value in `authcrypt` at all except proof of sender DID owning, but without unique preliminary data from recipient this proof doesn't make a lot of sense.

> Reuse of epk/cek (or iv/tag) is not recommended and just opens the door to security holes in the protocol. I don't agree with proposal.

For EPK it isn't true. JWS spec proposes to use single EPK for all recepients in one message. Maybe @AnomalRoil can judge us here.

>  But even if we do have such registry, calling many times H() can be quiet expensive as it must be computed for as many incompatible senders in the registry prior to getting the right one (imagine a registry of 1 million DIDs and the right sender is the last one, this means 1M x H() calls which will cost a huge performance hit).

As i said you know possible group of DID just because it is n-wise or pairwise connection. Calculation of 3 or even 300 H will be about 10000 times cheaper than performing of 3 additional ECDH operations. 

> To conclude, imho, Anoncrypt(Authcrypt()) is the best way to secure skid.

I think i provided serious arguments agains it. `Anoncrypt(Authcrypt())` requires 2 times more ECDH operations and as a result it requries 2 times more electricity that is quite critical for a lot of use case (IoT for example).

My approach can require some changes in `Pairwise establishing` and `DID rotation` processes you have in mind. I think we can avoid double encryption at all and significantly simplify Forward protocol.

**Comment by vimmerru** [comment]
BTW,

> To conclude, imho, Anoncrypt(Authcrypt()) is the best way to secure skid.

I think for DID Comm v2 it is good approach, my proposals only about v3+

**Comment by awoie** [comment]
Can we conclude this discussion by appreciating that `anoncrypt(authcrypt())` is a pragmatic approach for DIDCommV2 but we will work towards a better option for the next version? @dhh1128 @vimmerru is there any language change you'd suggest for DIDCommV2, or can we close this issue?

**Comment by vimmerru** [comment]
I think we should clearly state that without` anoncrypt` the property of sender protection will bot be achieved and recommend use `anoncrypt(authcrypt())` as a default approach.

I still suggest to review possibility re-use EPK for ECDH-1PU and ECDH-EC that will make  `anoncrypt(authcrypt())` 2 times more efficient.

@AnomalRoil what do you think about this ^

**Comment by Baha-sk** [comment]
>For EPK it isn't true. JWE spec proposes to use single EPK for all recepients in one message for ECDH-EC. Maybe @AnomalRoil can judge us here.

yes, this is the example in Appendix B in of ECDH-1PU, the epk is shared for both recipients in the same envelope. Probably i misunderstood your statement:

>Potentially we can consider re-usage of ephemeral keys or other secrets used for ECDH-1PU to reduce amount of crypto operations

 I thought you meant re-using outside of the JWE envelope, ie in subsequent envelopes, this is what I'm opposing.

Currently in DIDComm, for every message we send (authcypt), we create separate forward message (using a dummy ed25519 key as sender for authcrypt again since anoncrypt format was not defined in V1). The plan is to use ECDH-ES as a real anoncrypt for the forward message. 

I wouldn't share epk key between the original and forward messages though since the forward message is intended for mediators (routers) and the original is for end recipients.

> Calculation of 3 or even 300 H will be about 10000 times cheaper than performing of 3 additional ECDH operations.

not sure about that, if we're talking about querying a storage to fetch 300 did docs from the didConnections store, it can be costly. ECDH's cost is in the milliseconds and doesn't require any storage querying.

**Comment by ashcherbakov** [comment]
> The plan is to use ECDH-ES as a real anoncrypt for the forward message. This seems to match Anoncrypt(Authcrypt()).

Actually `Forward` and `Anoncrypt(Authcrypt())` to protect the sender ID are different:
-  `Anoncrypt(Authcrypt())`: both auth and anon crypt are done for the **end recipient keys** (Bob), so that only Bob can know the sender ID (that's why we have the outer `anoncrypt`)
- `Forward` is an **anoncrypt** for the **Bob's routing keys (mediator keys)**

So, `Forward(authcrypt)` doesn't protected the sender ID from the Bob's mediator to know it. Only `Forward(Anoncrypt(Authcrypt))` protects it. 
So, in order to protect the key in case of Forward protocol usage, there will be **more than one anoncrypt**.

> I wouldn't share epk key between the original and forward messages though since the forward message is intended for mediators (routers) and the original is for end recipients.

Yes, we are not suggesting to share the `epk` between Forward and original messages.
What we suggest in Item 4 is to consider sharing the `epk` between `anon` and `auth` crypts as part of protect-sender-id envelope (`Anoncrypt(Authcrypt())`), where both anon and auth crypts are for the same recipient (Bob). 

> ECDH's cost is in the milliseconds 

It may be much slower for embedded or low power devices. See, for example [link](https://csrc.nist.gov/csrc/media/events/lightweight-cryptography-workshop-2015/documents/presentations/session7-vincent.pdf).
ECDH can take up to 1000ms, and if you have multiple keys, plus `anon(auth)` envelopes, it can be a serious problem.

**Comment by AnomalRoil** [comment]
> I still suggest to review possibility re-use EPK for ECDH-1PU and ECDH-EC that will make `anoncrypt(authcrypt())` 2 times more efficient.

Re-using the same `epk` for both the ECDH-1PU and ECDH-ES key agreements when they are both used _in the same DIDComm message_ isn't a problem, as long as that `epk` is only used for that message. (Otherwise it could hurt forward secrecy.)

> For pairwise or even n-wise communication when recipient party knows in advance the sender DID (or possible sender DIDs) we can use H(KeyURI, IVcek, TAGcek) as SKID. Recipient can iterate over sender DIDDoc/DIDDocs and find a key that corresponds to hash.

Hashes are super fast, which means it could also lead to bruteforce attacks that would de-anonymize the sender easily if using a DID that is publicly available. The IVcek and the TAGcek aren't "secret", so the mediator / intermediaries can see them, allowing for an easy bruteforce _à la dictionnary attack_, using the DID registries to populate the dict.
I'm not a big fan of this idea.

**Comment by Baha-sk** [comment]
>Forward is an anoncrypt for the Bob's routing keys (mediator keys)

We agree on this. 

> So, Forward(authcrypt) doesn't protected the sender ID from the Bob's mediator to know it. Only Forward(Anoncrypt(Authcrypt)) protects it.

If we say Forward is equal to Anoncrypt, then `Forward(Anoncrypt(Authcrypt())) == Anoncrypt(Anoncrypt(Authcrypt()))` which is duplicating `Anoncrypt()` call. I don't think this we want to call it twice though. Forwarding the agent message is simply `Anoncrypt(Authcrypt())`.

What I wanted to emphasize in my previous comment is current DIDComm (pre V2) implementations are using a dummy sender key to build authcrypt() message for forwards to mimic anoncrypt, ie we're currently doing `Authcrypt(Authcrypt())`. Rather, in DIDComm V2, we should be using ECDH-ES to make forward messages `Anoncrypt()` in order to have a real Anoncrypt(Authcrypt()) call.

Anoncrypt(Authcrypt()) is sufficient to anonymize the sender kid (skid).

>> I still suggest to review possibility re-use EPK for ECDH-1PU and ECDH-EC that will make anoncrypt(authcrypt()) 2 times more efficient.

> Re-using the same epk for both the ECDH-1PU and ECDH-ES key agreements when they are both used in the same DIDComm message isn't a problem, as long as that epk is only used for that message. (Otherwise it could hurt forward secrecy.)

In reality Anoncrypt(Authcrypt()) is not called subsequently as is. It's rather in this order:
```
msg = Authcrypt(payload)
...
FordwardMsg(msg)

// whereForwardMsg is
ForwardMsg(msg) {
   envelope=Anoncrypt(msg)
   send(envelope)
}
```

I don't think it's a good idea to export `epk` and drag it around till `Anoncypt(msg)` is called, it's not standard to share around `epk` for the same payload. 

`Anoncrypt()` and `Authcrypt()` should be independent and atomic functions.

**Comment by ashcherbakov** [comment]
> If we say Forward is equal to Anoncrypt,

Technically, Forward is Anoncrypt but for **different keys** than original envelope.

> Forward(Anoncrypt(Authcrypt())) == Anoncrypt(Anoncrypt(Authcrypt())) which is duplicating Anoncrypt() call. I don't think we want to call it twice though. 

This Anoncrypts are for **different keys**:
- the first one is for the same keys as authcrypt, that is **for original recipient** (Bob)
- the second one (Anoncrypt from Forward) is for the **Bob's mediator keys**

> Anoncrypt(Authcrypt()) is sufficient to anonymize the sender kid (skid).

If by Anoncrypt here you mean Anoncrypt as part of Forward, that is Anoncrypt for Bob's mediator keys, then it's **not enough** to anonymize the sender kid (skid), as the **Bob's mediator will know the sender key**.
The only way to anonymize the sender kid, is to make sure that only the final recipient (Bob), and not any mediators can read the skid. The current proposal means that additional Anoncrypt for Bob's keys should be performed.

**Comment by awoie** [comment]
I agree that Forward is with a different key/DID. The goal of the anoncrypt(authcrypt(msg)) construct was to prevent the mediator from inspecting the sender of the message. IMO, with the Forward construct (only), identifying the sender would still be possible.

**Comment by Baha-sk** [comment]
in this case will need to do `Forward(Anoncrypt(Authcrypt()))` where `Forward()` uses Bob's mediator keys and `Anoncrypt(Authcrypt())` use Bob's own keys. 

It's an additional encryption step. @ashcherbakov, @awoie you're both right.

**Comment by awoie** [comment]
Resolution from DIDComm WG meeting, August 23rd:
- Explain why each of the envelope forms are needed, considerations, purpose, e.g. anoncrypt (to hide sender), and forward message
- add some language that we will work on better solution later to protect sender in a different version of the spec

-> PR needed.

**Comment by awoie** [comment]
@ashcherbakov pls let us know if you are fine with the resolution

**Comment by ashcherbakov** [comment]
We are fine with the resolution and using `anoncrypt(authcrypt)` to protect sender ID for the current version of the spec.
