### ISSUE TITLE
Forcing KeyAgreement and transport crypto doesn't look nature in the scope of DID Specification

### ISSUE THREAD

**Issue by vimmerru** [decentralized-identity/didcomm-messaging#221]
Hi,

According DID Spec KeyAgreement method is a pluggable specification, but I see we are trying force ECDH-1PU here despite a fact that method in examples forces direct ECDH.

**Comment by OR13** [comment]
regarding did core, `keyAgreement` is a relationship that is expected to container verification material that can support `deriveSecret` / `ECDH`.... I don't think it says anything preventing ECDH-1PU....

I believe DIDComm supports `ECDH-ES` as well...

**Comment by vimmerru** [comment]
>  I don't think it says anything preventing ECDH-1PU

It doesn't saying anything that ECDH-1PU must be forced. Recent DID Comm is deeply relying on ECDH-1PU and seems there is no ECDH-ES option. ECDH-1PU is the solution for repudiation auth as well as for forward secrecy.

**Comment by vimmerru** [comment]
What if i forced to use RSA (valid option for DID spec)? Any option in DID Comm?

**Comment by Baha-sk** [comment]
[key wrapping](https://github.com/decentralized-identity/didcomm-messaging/blob/master/docs/spec-files/encryption.md#key-wrapping-algorithms) in the DIDComm specs offers both ECDH-ES (for anonymous encryption) and ECDH-1PU (for authenticated sender encryption) algs.

> What if i forced to use RSA (valid option for DID spec)? Any option in DID Comm?
AFAIK, we don't want to support RSA.

**Comment by vimmerru** [comment]
>  we only want to support NIST approved EC keys.

For your understanding of my position. We have logical problem here. Top level specification says that crypto is pluggable and you can use any crypto you want. It should just be present in https://www.w3.org/TR/did-spec-registries/. But dependent specification only forces "NIST approved curves" and "ECDH-1PU" only for authcrypt.  Also in this registry there is nothing about ECDH-1PU.

Just "curve" isn't enough. Signature and authcrypt schema is quite important part of crypto. You can compare "ECDSA" and "EdDSA" and a lot of examples of quite different behaviour on the same curve. 

I can't say that "NIST approved curves" and "ECDH-1PU" is something wrong, but for significant part of the world "NIST approved"="weak". Usually there is much more trust to opinionated NaCl or similar top level primitives. There is a proof that ECDH-1PU have critical vulnerability in v3 draft. Is there any proof that v4 is good enough?

What if critical vulnerability will be found in v4? It isn't criticism, but behaviour we choice here is quite important for design of DID Comm libraries stack.

**Comment by Baha-sk** [comment]
@vimmerru, I meant from a DIDComm perspective. The [DID spec registries](https://www.w3.org/TR/did-spec-registries/) are different than DIDComm Messaging.

**Comment by Baha-sk** [comment]
>I can't say that "NIST approved curves" and "ECDH-1PU" is something wrong, but for significant part of the world "NIST approved"="weak". Usually there is much more trust to opinionated NaCl or similar top level primitives. There is a proof that ECDH-1PU have critical vulnerability in v3 draft. Is there any proof that v4 is good enough?

For this reason we use at least 32 bytes keys as opposed to a smaller, and more vulnerable 16 bytes keys. We know that AES128-GCM is vulnerable. Originally we intended to use AES256-GCM to mitigate this (back when v3 was out). As part of 1PU v4, we switched to AES256-CBC+HMAC-SHA512 which allows for compactly committing authentication to protect the identity of the sender with the recipients. 

We would love to use a more cutting edge alg (eg: Xchacha20Poly1305 + Blake2b), but we can't require it since it's not NIST/FIPS approved and not part of JWE specs anywhere.

**Comment by dhh1128** [comment]
I am less confident about the nature of the crypto here than some other experts, so I won't comment on that part of the topic except to say that I am glad we are using 32-byte keys and disallowing 16-byte.

I wanted to comment on the general relationship between DIDComm and the DID spec.

It is NOT a goal of DIDComm to support every possible type of DID. It IS a goal to support a reasonable number of secure DID methods, and I think we will easily achieve that. But if there's a DID method that wants to use a type of crypto that we consider insecure or impractical for some reason, the answer will be, "Sorry, DIDComm doesn't allow that." That's the answer for RSA, for example. RSA can be used in highly secure mode -- but the key sizes are so big that they become impractical to use in some DIDComm scenarios, and we're not going to fix that. It's simpler to just limit our focus to EC for now.

In the long run, we want DIDComm to support other key types and other algorithms. For example, we know there are quantum-secure options we will eventually need to support. But that's not a problem for today; it's a problem for tomorrow. Right now we are just picking enough options that are "good enough" that we can claim security similar or greater in strength to the options offered by Signal, TLS, commonly used SSH configs, etc.

To me, the most important question you asked, @vimmerru , is the one about whether 1PU draft 4 is solid. It has been through some amount of peer review -- but we don't know how much, and we don't know whether a vulnerability is lurking. So I think it IS important to ask what will happen if a vuln is discovered there. Right now I am thinking that the libraries we're writing will all have to be upgraded, and there will not be a way to carry on conversations with other parties that haven't been patched. And that may not be a very good answer.

**Comment by TelegramSam** [comment]
This was inferred in the discussion, but not said directly: DIDComm V2 by design supports pluggable crypto, but then places limitations on the crypto allowed. Why? Because we know we'll need to move to something better eventually (as new crypto will always be progressing), but want to benefit from a narrow implementation pathway as we get going.

**Comment by awoie** [comment]
@vimmerru does this answer your question, can you we close this issue? Let us know about what you feel is missing in the specification, otherwise we will close this issue.

**Comment by TelegramSam** [comment]
Closed after discussion in WG 20211101. Please reopen if closed incorrectly.
