### ISSUE TITLE
Are we going to address Internationalization / localization?

### ISSUE THREAD

**Issue by TelegramSam** [decentralized-identity/didcomm-messaging#226]
DIDComm V1 has a way to indicate language and alternative translations within a message. Is that something we wish to include in v2?

**Comment by kdenhartog** [comment]
We'll need to decide if we want to defer this issue or set it as a v2 issue as well. I tend to think we're going to need to address this in a baseline V2 although I have no expertise in this area.

**Comment by kdenhartog** [comment]
@dhh1128 said on #152
> We need enough i18n support in DIDComm v2 to prevent a variety of incompatible solutions from arising. We should explain how a DIDComm protocol can solve 2 problems:
> 
>     1. Clarify the lang of a field ("These instructions for the loan applicant are in Spanish.")
> 
>     2. Allow fields in a message to have the same semantic role, but provide content in different languages. ("Here's the French equivalent of the Spanish instructions field.")
> 
> 
> This is likely to require much less complexity than the i18n mechanism proposed for DIDComm v1 -- but perhaps it will use a subset of it?

Moving the comment here so that we can consolidate the discussions

**Comment by TelegramSam** [comment]
closed, given the approved content.
