### ISSUE TITLE
need clarification about encrypted(encrypted(payload)) in mime types table

### ISSUE THREAD

**Issue by dhh1128** [decentralized-identity/didcomm-messaging#236]
We don't describe the `encrypted, then encrypted` scenario that's described in the mime types table. We need to explain ourselves more.

I believe our intention with it is always `anoncrypt(authcrypt(data))` option, where “data” might be a signed message or a plaintext message. It is an unnatural behavior that is only used in one case, which is to hide the key of the sender from the final mediator in a delivery route.

Do others agree that this is what we meant? If so, I will raise a PR to add some explanatory language about it.

**Comment by dhh1128** [comment]
tagging @vimmerru

**Comment by mirceanis** [comment]
That's the way I interpreted it too.
In our implementation we define the possible message "packing" options as:
* plain
* signed
* anoncrypt
* authcrypt
* anoncrypt + signed
* anoncrypt + authcrypt

**Comment by vimmerru** [comment]
@dhh1128 One additional point, `anoncrypt(authcrypt(data))` and `authcrypt(data)` and `anoncrypt(authcrypt(sign(data)))` have one mime type. If we force only few and exact wrappings should it be different mime types?

Also what we should do if authcrypt, sign and plain messages here use different `from`? Or if `from` missed in plain text? How `trust` is combined when we remove authcrypt, anoncrypt or sign envelopes? I think spec should describe it also.

**Comment by dhh1128** [comment]
>have one mime type. If we force only few and exact wrappings should it be different mime types?

I don't think so. We don't want people to know what's inside an outer layer of encryption; from the perspective of someone who may or may not be able to decrypt it, all of these should look the same. It is only someone who is capable of peeling away the wrappers that should know more detail.

**Comment by ashcherbakov** [comment]
We should probably address the following the Spec: [Possible-nested-message-combinations](https://hackmd.io/aD4TzKRhT1ma2ERl6EKU_g?view#Possible-nested-message-combinations)

**Comment by awoie** [comment]
From my perspective, all DIDComm message types are just tools for higher-level protocols. IMO, it would make sense to recommend packing methods to achieve certain properties (e.g., authcrypt(data) as default for identifier auth, anoncrypt(authcrypt(data)) to hide sender  etc.) but let the higher-level protocols to decide which properties are needed, e.g., sender authentication.

To your question @dhh1128, yes, it was the intend to use anoncrypt(authcrypt(data)) for sender anonymity. And I also agree, we could improve language and in particular the table a little bit better.
