### ISSUE TITLE
Should implementation encrypt-decrypt attachments in JWE format or verify JWS signatures?

### ISSUE THREAD

**Issue by vimmerru** [decentralized-identity/didcomm-messaging#239]
20.2 Section of protocol describes attachment structure and here can be jwe, jws field. 

1. Does JWE have any relation to DID Comm protocol and DID keys of communicating DIDs?
2. Should implementation encrypt-decrypt attachments JWE format or verify JWS signatures? Or it is up to application?
3. jwe field described mandatory. Is it correct?

**Comment by dhh1128** [comment]
Anybody can sign an attachment. Alice could attach a brochure for the university she studied at (without the university's help, but signed by the university long ago). So the signer of an attachment doesn't have to have any relation to the sender or receiver of a DIDComm message, and doesn't have to have a DID.

I don't know anything about encrypted attachments; I thought we only supported JWSes in a special way. All other streams of bytes are just streams of bytes -- could be encrypted or not, but DIDComm doesn't care. Can you point to where in the spec it talks about JWE attachments, so I can go study them more? (Maybe this is related to the payloads attached to a `forward` message, in whcih case the attachment is indeed a JWE -- but one produced by the `pack()` function of a DIDComm impl library?)

**Comment by vimmerru** [comment]
@dhh1128 Just read https://identity.foundation/didcomm-messaging/spec/#reference-2

**Comment by vimmerru** [comment]
@dhh1128 `lastmod_time` parameter is also noted as mandatory that looks suspicious

**Comment by dhh1128** [comment]
`lastmod_time` should be optional. 

I have raised #240 to clarify various details about attachments.

**Comment by kdenhartog** [comment]
It could be the case that we left encrypted attachments text in from when we were talking about using them for message forwarding to split the encryption a bit as well. Could be worth reviewing the git history to see how this portion of text got in and for additional context about it. I don’t remember the specifics either.

**Comment by TelegramSam** [comment]
I do not think we should process encrypted attachments (by default) when decrypting a message.  

Verifying JWS signatures could be useful, but note that the signer may not be the message sender - that should be indicated in the JWS signature itself.

**Comment by dhh1128** [comment]
I think the answer to Slava's original questions 1 and 2 is "No", and I recommend that we close the ticket.

**Comment by TelegramSam** [comment]
Agree on closing.
