### ISSUE TITLE
Need to explicitly define security requirements of DIDCommV2

### ISSUE THREAD

**Issue by kdenhartog** [decentralized-identity/didcomm-messaging#245]
After reading through #243 entirely, I've come to realize it's probably best if we get @AnomalRoil to help us out with defining explicit security requirements for the **envelope layer only**. I think by doing this we'll be able to identify potential conflicts that we never noticed as well as explicitly define the architectural security requirements we have. So far these are the ones that pop into my head.

MUST have weak perfect forward secrecy. SHOULD have Perfect forward secrecy.
MUST have message confidentiality
MUST have message integrity
MUST have message authentication (In the traditional cryptographic definition used - basically needs to use Authenticated encryption)
MUST default to using repudiable identifier authentication at the envelope layer (authcrypt style "message authentication" - how we've traditionally used the terminology)
MUST be able to add non-repudiable identifier authentication at the envelope layer (digital signatures - this is what nesting gets us)

Note, I'm explicitly saying "identifier" rather than "identity" here. What I mean here is "identifier authentication" is that the recipient can verify continuity of the identifier. When I say "identity authentication" I mean the higher order binding of an identifier to other attributes which is traditional described as "exchange some VCs to prove who you are" which I considered out of scope for this part. It's necessary for the "prevent MITM" part - but we could still perform some formal verification at this layer by making this discrepancy by adding an assumption "Identifier has been bound to a trusted identity" to the verification engine.

I'm sure there are other ones that I'm missing. @dhh1128 @andrewwhitehead @Baha-sk @awoie can you add any ones that I've missed - even if they may be contentious so we can start with an all encompassing list and remove as necessary.

@vimmerru @jovfer @ashcherbakov @devin-fisher @swcurran @TelegramSam @nage @mikelodder7 @SvenHammann90 thinking you guys might have some to provide as well.

**Comment by kdenhartog** [comment]
Also for your reference @AnomalRoil, @SvenHammann90 performed a formal verification of the protocol awhile back and here is his findings. https://github.com/SvenHammann90/SSI/tree/master/RWOT_9

**Comment by OR13** [comment]
I've also used https://prosecco.gforge.inria.fr/personal/bblanche/proverif/ these can be fun to write if you like learning a bit of a new language.

**Comment by dhh1128** [comment]
+100 to this effort.

I think your initial cut of requirements is very good, @kdenhartog .

**Comment by kdenhartog** [comment]
Another one I thought off that's worth at least mentioning. We may end up dropping it though because it's more along the lines of "MUST NOT use a known attack" which is a given when it comes to security.

When utilizing repudiable identifier authentication the envelope layer MUST NOT be susceptible to a key compromise impersonation (KCI) attack.

**Comment by AnomalRoil** [comment]
That's definitively a must-have list, indeed. I've actually already started digging into the desirable/undesirable security features we might want to consider for DIDComm, in order to try and have a more refined view of its "security goals".

**Comment by AnomalRoil** [comment]
> When utilizing repudiable identifier authentication the envelope layer MUST NOT be susceptible to a key compromise impersonation (KCI) attack.

This seems like a difficult goal to achieve without some kind of out of band communication/pre-shared secret based protocol...

Deniability is a notoriously hard property that we can split into multiple parts:
- participant repudiation: a party can deny having taken part in a given communication session
- message repudiation: a party can deny having sent a specific message
- message unlinkability: if someone is convinced a given message was sent by a given party, it doesn't allow them to infer the authorship of any other message

But on the other hand, ECDH-based protocols are notoriously prone to KCI attacks.
For instance ECDH-1PU is vulnerable to it and recommands nested JWS signatures over the content as a workaround to avoid it, but these are not deniable at all...  

So, I'm not really sure we wants to have such a strong constraint in our design.

**Comment by kdenhartog** [comment]
> > When utilizing repudiable identifier authentication the envelope layer MUST NOT be susceptible to a key compromise impersonation (KCI) attack.
> 
> This seems like a difficult goal to achieve without some kind of out of band communication/pre-shared secret based protocol...
> 
> Deniability is a notoriously hard property that we can split into multiple parts:
> 
>     * participant repudiation: a party can deny having taken part in a given communication session
> 
>     * message repudiation: a party can deny having sent a specific message
> 
>     * message unlinkability: if someone is convinced a given message was sent by a given party, it doesn't allow them to infer the authorship of any other message
> 
> 
> Here we are really targeting the first one, which implies the second one. The third one might be something to discuss whether or not it's a requirement for us or not (somewhat related to the `thid` / `pthid` discussions maybe?)
> 
> But on the other hand, ECDH-based protocols are notoriously prone to KCI attacks.
> For instance ECDH-1PU is vulnerable to it and recommands nested JWS signatures over the content as a workaround to avoid it, but these are not deniable at all...
> 
> So, I'm not really sure we wants to have such a strong constraint in our design.

That sounds like a good way to frame it to me. I definitely only know enough to be dangerous in this area so I'll defer to your expertise on this.

**Comment by AnomalRoil** [comment]
I'm surprised that neither Tamarin nor Proverif catched the PFS issue discussed in #303 BTW, what are your thoughts on this @OR13 @SvenHammann90 ?

**Comment by SvenHammann90** [comment]
Hi all,

Indeed, the Tamarin models were looking at the protocols on a higher level
of abstraction, and before clear security properties were even defined.

Kind Regards,
Sven

**Comment by TelegramSam** [comment]
TODO: Add Security Considerations section.

**Comment by TelegramSam** [comment]
Discussed WG 20220131. Non-normative intro section at top can include basic goals/requirements, and any more detailed discussion can be contained in errata.

Needs a PR to make sure that's in the intro.

**Comment by dhh1128** [comment]
I've introduced a simple PR (#327) that fixes this with a simple but clear articulation of all the properties that are not controversial. I believe perfect forward secrecy is a topic unto itself (see #307), so I propose that this be considered adequate for the time being. We can add additional details in errata if needed.

**Comment by dhh1128** [comment]
Fixed by #328

**Comment by kdenhartog** [comment]
It's been awhile since I've looked at this spec, but I think that could work. If this is the case it would be useful make this a more broadly adopted approach. There may be potential to drop ECDH-1PU as well and just leverage ephemeral DIDs with normal ECDH-ES for encryption and authenticity guarantees could come via a DIDComm protocol instead. The one tricky aspect to that approach of having an ephemeral encryption identifier and a persistent identifier is that there's a tradeoff made where the cryptography and security guarantees is no longer handled via the external wrapper layer and it may have effects on the repudiated messages mode.
