### ISSUE TITLE
#alternative-endpoints needs an extra explanatory sentence or two

### ISSUE THREAD

**Issue by dhh1128** [decentralized-identity/didcomm-messaging#247]
In https://identity.foundation/didcomm-messaging/spec/#alternative-endpoints, we have a discussion of how to represent mediators in conjunction with `serviceEndpoint`. Two examples are given. One puts `somemediator`'s DID in `serviceEndpoint` WITHOUT adding any keys to `routingKeys`; the explanatory text says that `somemediator`'s keys must be appended to `routingKeys` after resolution of the mediator's DID doc. The other example shows `somemediator`'s DID in `serviceEndpoint`, PLUS a key for `anothermediator` DID in `routingKeys`; the explanatory text says that this is a pattern used for rewrapping.

My concern is that there is a third possibility: a DID for `somemediator` is in `serviceEndpoint`, and a key for `somemediator` (NOT `anothermediator`) appears in `routingKeys`. What should happen then? Does this mean we want to use `somemediator`, but restrict our mutiplex encryption to only one of the keys in `somemediator`'s DID doc? Is it legal?

I don't feel comfortable allowing this odd behavior. I want a sentence that prohibits it (any DID that appears in `serviceEndpoint` is never allowed to put keys in `routingKeys`). But before I submit a PR to that effect, I wanted to check to see if my understanding matches the intent of others in the community.

Tagging @TelegramSam @kdenhartog @ashcherbakov @swcurran

**Comment by swcurran** [comment]
I don't think the section is particularly clear. However, I'm not sure your concern is real around the third case. If there is a DID as the serviceEndpoint, you put it's keyAgreement key in the routingKeys, end of story.  You don't check to see if the key is already there and don't do it in that case.  If that is a mistake, that's the didController's problem.

Perhaps a statement -- "you are an idiot if you do this", or the more general "don't put in a combination that won't work", but I don't see it as a huge concern.

**Comment by dhh1128** [comment]
>If there is a DID as the serviceEndpoint, you put its keyAgreement key in the routingKeys, end of story.

That is what I thought. But neither of the examples in this section show that behavior. Example 1 shows a DID in the serviceEndpoint, with nothing in `routingKeys`; example 2 shows a DID in the serviceEndpoint, and the key *from a different DID# in routingKeys.

So that's why I opened the issue...

**Comment by swcurran** [comment]
I don't quite understand the concern. 

Using the rule, in the first case, you have an implied routingKeys array with one entry -- the keyAgreement from the serviceEndpoint DID.  With the second, you the keyAgreement from the serviceEndpoint is appended to the existing routingKeys array.

Perhaps you are looking for an example of the implicit service block that shows the implied routingKeys added?

That's how I interpret this, but perhaps I'm missing something?

**Comment by dhh1128** [comment]
I think the source of our misalignment may boil down to what you meant vs. what I understood you to mean when you said, "If there is a DID as the serviceEndpoint, you put its keyAgreement key in the routingKeys, end of story."

My interpretation of this rule was that you actually change the DID Doc content when you "put its keyAgreement key in the routingKeys". I am guessing that what you meant is that you don't change the DID Doc content -- you only change your intepretation of the content. Thus you can have literal text that says one thing, but implicit meaning that's different. Did I identify the divergence in our thinking accurately?

The implictness vs. explicitness is what I think is poorly defined. If we want implicitness, we need to make it very clear how it works. Right now we have implicitness that is just understood to work that way, which is a bad combination.

**Comment by TelegramSam** [comment]
> Implicit handling, allowing changing the endpoint DIDDoc to (implicitly) update the routingKeys in this DIDDoc.

This is the only viable option in my mind.

Background: allowing the DID to be placed in the ServiceEndpoint allows for the mediator to update their actual endpoint and the corresponding key (for use in routing) without having all dependant DID Documents updated.

I think we can revise the text to indicate that the keyAgreement key in the `serviceEndpoint` must be _considered_ to be prepended to the `routingKeys` by the sender. Also, I agree that an example would be helpful.

If this is agreeable, I'll prep a PR.

**Comment by swcurran** [comment]
Thanks, Sam -- works for me.  I was trying to be neutral in above, but I agree with that view.

**Comment by dhh1128** [comment]
That's a good outcome. I wasn't really arguing for a position; I was arguing that the text was ambiguous. So some extra explanation will be good.

**Comment by TelegramSam** [comment]
The current docs state:

> Using a DID for the serviceEndpoint is useful when using a mediator. The DID should be resolved, and services with type of "DIDComm" will contain valid serviceEndpoints. The keyAgreement keys of that DID Document should be appended at the end of the routingKeys section from the message recipient's DID Document as per the process in [Sender Forward Process]. The key advantage with this approach is that a mediator can rotate keys and update serviceEndpoints without any updates needed to dependent recipients` DID Documents.

I believe this is what we've described above (though above I've errantly said prepended instead of appended), but was already in the document. @dhh1128  I've also reviewed both examples, and I believe them to be technically correct. I've submitted a PR with very minor clarifications, but I'm unaware of other errors to fix. Can you review to see if I've missed something?
