### ISSUE TITLE
RFC 0023: need to send DID Doc as bytes, not as data structure

### ISSUE THREAD

**Issue by TelegramSam** [decentralized-identity/didcomm-messaging#25]
Original Issue: https://github.com/hyperledger/aries-rfcs/issues/243

**Comment by kdenhartog** [comment]
the initial-values query parameter is an alternative method for handling this I believe.

**Comment by TelegramSam** [comment]
At this point, it's the preferred method. I'm leaving this here till that becomes more solid.

**Comment by TelegramSam** [comment]
Closed in WG Meeting 2020-11-02.
