### ISSUE TITLE
Common connection managment protocol

### ISSUE THREAD

**Issue by kdenhartog** [decentralized-identity/didcomm-messaging#250]
Moving this topic here since it's separate from the discussion I was originally asking in #220 but is something I wanted to bring up for awhile.

@TelegramSam originally asked in #220 
 
> 
> @kdenhartog What do you see as the division of responsibility between the feature discovery protocol vs OOB?
> 
> I have been thinking of OOB as only containing the info needed to bootstrap into a deeper interaction around feature discovery.

That's the thing, I don't see them as separate really anymore. I see them as all a single group of messages which are used to convey some logic about the connection, but the connection configuration isn't static. It also can be updated, and the OOB message can be used for both the setup and the updating is my thinking.

Here's an example of what I mean. All of the data below is connection related and could theoretically be included within the initial message sent as just a signed message.
```json
{
  "type": "https://didcomm.org/connection-config/v1",
  "id": "<id used for context as pthid>",
  "body": {
    "label": "Faber College",
    "accept": [
      "didcomm/aip2;env=rfc587",
      "didcomm/aip2;env=rfc19",
      "didcomm/v2"
    ],
    "handshake_protocols": [
      "https://didcomm.org/connections-config/1.0"
    ],
    "preferred_key_type": [ "X25519", "P-384"],
  }
}
```

Now let's say, the sender what's to be able to update the protocols they support now that a message has been sent (because they didn't want to reveal all of the ones they support in plaintext. That message could look like this:

```jsonc
{
  "type": "https://didcomm.org/connection-config/v1",
  "id": "<id used for context as pthid>",
  "body": {
    "label": "Faber College",
    "accept": [
      "didcomm/aip2;env=rfc587",
      "didcomm/aip2;env=rfc19",
      "didcomm/v2"
    ],
    "handshake_protocols": [
      "https://didcomm.org/connections-config/1.0"
    ],
    "preferred_key_type": [ "X25519", "P-384"],
    "supported_protocols": [ // indicates which messages the sender can receive
    "https://didcomm.org/issue-credential/" // indicates support for all versions of a protocol
    "https://didcomm.org/present-proof/v1" // indicates support for a particular version of a protocol
    "https://didcomm.org/messagepickup/1.0/list-pickup" // indicates support for a particular message in a protocol
    ]
  }
}
```

Let's say that the sender now wants to drop support for old versions of didcomm, they could indicate that by using the following:

```json
{
  "type": "https://didcomm.org/connection-config/v1",
  "id": "<id used for context as pthid>",
  "body": {
    "label": "Faber College",
    "accept": [
      "didcomm/v2"
    ],
    "handshake_protocols": [
      "https://didcomm.org/connections-config/1.0"
    ],
    "preferred_key_type": [ "X25519", "P-384"],
    "supported_protocols": [
    "https://didcomm.org/issue-credential/"
    "https://didcomm.org/present-proof/v1"
    "https://didcomm.org/messagepickup/1.0/list-pickup"
    ]
  }
}
```

Or say they want to drop support for a protocol, they could do this:

```jsonc
{
  "type": "https://didcomm.org/connection-config/v1",
  "id": "<id used for context as pthid>",
  "body": {
    "label": "Faber College",
    "accept": [
      "didcomm/v2"
    ],
    "handshake_protocols": [
      "https://didcomm.org/connections-config/1.0"
    ],
    "preferred_key_type": [ "X25519", "P-384"],
    "supported_protocols": [
    "https://didcomm.org/issue-credential/v2" // now only supports the v2 issuance protocol
    ]
  }
}
```

The nice aspect about this is it makes it a common message format for all configuration data related to the management of the connection and is used only to indicate the sender's preferences, meaning no negotiation needs to occur. Instead a simple ack message or problem report could be sent back. Say for example no common crypto was supported, the recipient could send an error report indicating so.

Additionally, this becomes a very powerful method for setting up a connection after a 0-RTT protocol round. Say for example, a person has completed a 0-RTT style credential issuance protocol and would now like to indicate support for setting up a connection. They could go about that by just sending one of these messages (because they already got the did from the signed credential-offer message during the 0-RTT protocol).

The nice thing about this too, is that it makes for a very simple way to manage state for connections.

As an example, the internal data model that could theoretically be used to manage a connection with did:example:123 would be this:

```jsonc
{
    "theirDid": "did:example:123",
    "myPairwiseDid": "did:example:456",
    "myKeys": [
       {
         "keyId": "123456789",
         "didDocumentKeyId": "did:example:456#key1",
         "keyType": "Ed25519"
       },
       {
         "keyId": "987654321",
         "didDocumentKeyId": "did:example:456#key2",
         "keyType": "X25519"
       }
     ],
    "label": "Faber College",
    "accept": [
      "didcomm/v2"
    ],
    "handshake_protocols": [
      "https://didcomm.org/connections-config/1.0"
    ],
    "preferred_key_type": [ "X25519", "P-384"],
    "supported_protocols": [
    "https://didcomm.org/issue-credential/v2"
    ]
  }
```

The point being, one message can cover it all in my opinion hence the statement around not seeing them as different.

**Comment by kdenhartog** [comment]
Some other features that seem advantageous in here:

Service endpoint information,
Routing information (e.g. when you see a message with this key pass it to this device or store it for me and I'll come pick it up)
mediator logic

**Comment by dhh1128** [comment]
I feel conflicted.

I get the simplicity of what Kyle's describing here.

However, it's important to remember that OOB replaces the normal security and privacy of DIDComm with an alternative that it's up to the sender and receiver to manage (e.g., transmission of a signed plaintext message over email, https, the file system, or a QR code). By making this mechanism more and more powerful, we are tempting people to live outside mainstream DIDComm for increasingly common and important behaviors.

I think OOB has a place -- but I think it should be viewed as suboptimal for anything except initial setup, because it creates a dependency on a different security and privacy mechanism with unknown guarantees.

**Comment by TelegramSam** [comment]
> Additionally, this becomes a very powerful method for setting up a connection after a 0-RTT protocol round. Say for example, a person has completed a 0-RTT style credential issuance protocol and would now like to indicate support for setting up a connection.

I'm really unaware, given our adoption of 0RTT, what setting up a connection would entail.

I'm not a fan of this combination: it conflates a bootstrapping step with ongoing relationship management that should be handled with DID Doc updates and other protocols such as Feature Discovery.

**Comment by kdenhartog** [comment]
I think there's a reasonable argument to be made that conflating the envelope configurations (which ciphers, which formats, etc) and the higher level protocol configurations is likely not a good methodology. If it's possible, while maintaining privacy, to contain all configuration aspects in the did document service endpoint block then I think it's reasonable to assume that the OOB aspects become unnecessary since it can all be discovered in the did document.

I still need to re-read the discovery protocol V2 as well to see how that's shaping up.

**Comment by kdenhartog** [comment]
@dhh1128 I gave a quick read through the discover-feature-v2 protocol. In general, I like what it does and it combines well with what I'm thinking. More generally though it pointed out to me a common difference that we could reconcile here, and likely apply more generically across protocols. Currently when I'm reading through the [RFC-0557](https://github.com/hyperledger/aries-rfcs/tree/master/features/0557-discover-features-v2) it reads very much like a request-response architecture even though my understanding from @TelegramSam on the call today was that it doesn't need to be that way.

What this has pointed out to me is that in a peer-to-peer architectures there's two generic methodologies of how interactions can occur for a protocol.

The first is the obvious one, request-response which is very much like a GET request in HTTP.

The second one I think is less common, but still valid which is what I've proposed above. I refer to this as the notify-acknowledge pattern. This is very similar to how a POST works in HTTP. I POST some data to the server, and the server either acknowledges it or reports an error.

In the discover-features protocol the request-response is well documented and understood, and in the proposal above the second less common pattern of notify-acknowledge is used. I'm realizing that both are valid and in certain cases one or the other may make sense.

Just some general thoughts I've had on this since reading through it, what's your take on this view point?

**Comment by kdenhartog** [comment]
I think the general consensus on this is that we'd rather leave discover-features-v2 separate from the OOB invitation because the information that should be communicated in the various protocols should be different for the purposes of reducing information that's potentially publicly available if the two protocols were combined. Clsoing without addressing this.

**Comment by apelt** [comment]
There is already Out of Band Protocol 2.0 now (https://didcomm.org/out-of-band/2.0/) compliant with DIDComm v2. Is there also DID Exchange Protocol 2.0 somewhere?
