### ISSUE TITLE
Lack of examples / test vectors in DIDComm spec

### ISSUE THREAD

**Issue by ashcherbakov** [decentralized-identity/didcomm-messaging#251]
It would be great to add examples / test vectors to the spec, so that 
- developers implementing it can write the corresponding tests and have confidence in the implementation
- readers can understand the spec better and easier by means of examples

There are TBD comments in [Message Encryption Examples](https://identity.foundation/didcomm-messaging/spec/#examples) and [Message Signing Examples](https://identity.foundation/didcomm-messaging/spec/#examples-2). It would be great to add examples there, as well as in other places: Attachments, Routing (Forward protocol), etc.

**Comment by TelegramSam** [comment]
Agree on closing. Further discussion on types or specifics of test vectors can be tracked in new tickets.
