### ISSUE TITLE
Need more info about headers in anoncrypt (ECDH-ES) case

### ISSUE THREAD

**Issue by ashcherbakov** [decentralized-identity/didcomm-messaging#256]
The current spec provides details about common protected headers for authcrypt (ECDH-1PU) case: [link](https://identity.foundation/didcomm-messaging/spec/#ecdh-1pu-key-wrapping-and-common-protected-headers).
But there is no such info for anoncrypt (ECDH-ES) case. The general JWE/JWA specs don't specify what must be set for some of the headers, as it's up to application (see [link](https://datatracker.ietf.org/doc/html/rfc7518#section-4.6.2)).

So, we need to specify the following for anoncrypt (ECDH-ES) in the spec:
1) What common protected headers must be used  (`apv`, `apu`, `alg`, `epk`?)
2) What should be used as `apv` value
3) What should be used as `apu` value
4) Whether `alg` and `epk` must be in protected or per-recipient unprotected headers 
   - specific case: multiplex-encryption for multiple keys of potentially different types, where we may generate multiple epks for every recipient key type.

**Comment by dhh1128** [comment]
Excellent question.

Do you have any proposals, Alex?

**Comment by ashcherbakov** [comment]
As a reference, I would put an example of anoncrypt as defined in Aries RFC: [link](https://github.com/hyperledger/aries-rfcs/tree/main/features/0334-jwe-envelope#anoncrypt-using-ecdh-es-key-wrapping-mode-and-a256gcm-content-encryption). BTW I strongly believe we must have similar example for DIDComm spec, see #251.

As for proposal, there are multiple things here, and it's not that obvious:
1) I believe `alg` must be part of the protected header (as in ECDH-1PU).
2) I believe we must have `apv` in protected header (as in ECDH-1PU). The value can be the same as for ECDH-1PU ([link](https://identity.foundation/didcomm-messaging/spec/#ecdh-1pu-key-wrapping-and-common-protected-headers)): this represents the recipients’ kid list. The list must be alphanumerically sorted, kid values will then be concatenated with a . and the final result MUST be base64 URL (no padding) encoding of the SHA256 hash of concatenated list.
3) As the message is anoncrypt, and there is no static sender kid, probably we don't need to specify an `apu` value. Aries uses the sender's ephemeral key as apu, but it can be a problem in case of multiplex-encryption for multiple key types (see below).
4) If there is only one ephemeral key (either one recipient or all recipient keys are of the same type), then `epk` must be part of the protected header.
5) If there are multiple recipient keys of different types, where we may generate multiple epks (one per key type), then the current JOSE specs doesn't have any examples how to set `epk` in that case. Aries just puts the `epk` into the unprotected per-recipient headers, but is it safe to make it unprotected?

**So, we need to decide:**
1) Whether we require `apu` for anoncrypt (Item 3)
2) How to deal with Item 5. I believe we may ask @AnomalRoil's opinion here.

**Options for Item 5:**
- Don't support multiple epks at all, and assume encryption for only one key type. Not so good for real cases and adoption, but maybe safer as the JOSE spec doesn't define in details how to do it.
- Put epks into per-recipient unprotected headers as Aries does: [link](https://github.com/hyperledger/aries-rfcs/tree/main/features/0334-jwe-envelope#anoncrypt-using-ecdh-es-key-wrapping-mode-and-a256gcm-content-encryption)
- Put epks into protected headers. It's not clear what syntax to use for this.

**Comment by dhh1128** [comment]
This seems like a sensible proposal to me. I would like to support multiple `epk` values at some point, but since we don't have a way to do that in the JOSE specs at present, I am okay with beginning to implement with the assumption that we have only one.

**Comment by AnomalRoil** [comment]
> 5. If there are multiple recipient keys of different types, where we may generate multiple epks (one per key type), then the current JOSE specs doesn't have any examples how to set epk in that case. Aries just puts the epk into the unprotected per-recipient headers, but is it safe to make it unprotected?

"unprotected" actually means it's not part of the authenticated data. This is not a good idea in general because we usually wants to "bind" a given message to a given key. 
In the worst case scenario, an invalid curve attack might be carried out if we're not authenticated to ephemeral keys.
We're also opening up to more malleability, too much, maybe.
ECC public keys are very malleable, which is not always desirable. In our case we want to prevent malleability as much as possible.

I've notice that the JWK have the notion of "Sets": https://datatracker.ietf.org/doc/html/rfc7517#section-5 
Not sure how these are supported in general, but we might rely on them and in the case where the epk field is a set of JWK instead of a single JWK, then the recipients are supposed to pick the JWK within that set which is matching their own `kid`'s curve.

**Comment by ashcherbakov** [comment]
As a summary, we are going to proceed with ECDH-ES JOSE support in DID Comm under the following assumptions:
- Only one `epk` in protected header for all the recipients
- `apv` must be present in the protected header and calculated the same as in [ECDH-1PU case](https://identity.foundation/didcomm-messaging/spec/#ecdh-1pu-key-wrapping-and-common-protected-headers)
- `apu` will not present at all
- `alg` must be present in the protected header. There will be one and the same alg in protected header for all the recipients.

**Comment by AnomalRoil** [comment]
Sounds good for now. It should be noted this is restricting us to a single key type in the multi-recipient case and is a limitation of the implementation rather than the spec, tho.

**Comment by awoie** [comment]
I don't understand why `apv` and `apu` is required for anoncrypt and why `alg` needs to be in the protected header. Aries requires this for anoncrypt?

**Comment by TelegramSam** [comment]
It sounds like the solution is another section for ECDH-ES that mimics the excellent one  for ECDH-1PU:https://identity.foundation/didcomm-messaging/spec/#ecdh-1pu-key-wrapping-and-common-protected-headers

... but with the summary proposed by @ashcherbakov above.
