### ISSUE TITLE
Need repeatable methodology for new protocols

### ISSUE THREAD

**Issue by awoie** [decentralized-identity/didcomm-messaging#261]
This relates to #222 but since the protocols aspect is not part of the #222, I created a new issue with the following proposal.

The following might sound probably controversial but I'm wondering how those changes resonate with people in this group.

IMO, it would help if we would restructure the protocols section a bit to fix a couple of issues (e.g., forms of didcomm message -> when/which to apply; methodolgy for new protocols, making URI a transport, making invitation better fit since it is a bit different than other protocols)

Transport related restructuring was proposed [here](https://github.com/decentralized-identity/didcomm-messaging/issues/222#issuecomment-904719436).

Here are the proposed changes related to protocols...

Make OOB (invitation) a protocol rather than a standalone section.

Then, make a CORE protocols section with the following sub-sections:
1. Invitation (OOB)
2. Discovery
3. Trust ping
4. others if required (I don't see any yet)

In the protocols section, we should say that each protocol MUST define:

- if receiving agent requires sender anonymity OR sender authentication; defaults to sender anonymity.
- if receiving agent requires confidentiality of the message, i.e. at least anoncrypt but authcrypt also works; defaults to confidentiality. but no confidentiality is required for the invitation protocol for example.
- types of sender authentication, i.e., repudiable vs non-repudiable, although if not specified MUST default to authcrypt. Note, the invitation protocol likely does not require any protection.
- The above could be enforced by saying that if sender DID Doc has a keyAgreementKey, authcrypt MUST be used instead of non-repudiable signatures. the receiving agent can check that and even a normative test can be written.

**Comment by TelegramSam** [comment]
I believe this is satisfied with the reorganization of the protocols section and related content.
