### ISSUE TITLE
Remove mention of support for JSON-LD due to lack of implementations

### ISSUE THREAD

**Issue by kdenhartog** [decentralized-identity/didcomm-messaging#265]
I think we remove mention of JSON-LD in the spec and this issue is here to discuss that. I've not seen people using it in any way and given protocols require logical processing of messages above and beyond the semantics of the data model, I don't see what additional value this is buying us. In this case, JSON-LD seems to serve as more of a disadvantage than an advantage here.

**Comment by swcurran** [comment]
I just read this and had a "duh" moment.  I completely agree.  In the envelope layer, there is no need for this.

**Comment by TelegramSam** [comment]
Discussed WG 20211108.
