### ISSUE TITLE
Trust Ping protocol needs a `from` attribute

### ISSUE THREAD

**Issue by brianorwhatever** [decentralized-identity/didcomm-messaging#271]
In order to respond to a trust ping the receiver needs to know where to send the response. Is there a different way to determine the sender that I'm not aware of?

**Comment by swcurran** [comment]
In DIDComm2, all messages have a "from" in the header.  I assume that the trust ping message is assuming that.

**Comment by brianorwhatever** [comment]
Listed as optional here https://identity.foundation/didcomm-messaging/spec/#message-headers so maybe we just need to specify its required in the trust ping protcol section

**Comment by kdenhartog** [comment]
I've been operating on the same assumption you have @swcurran that a `from` is required as well. Keen to figure out what the expectation is for handling identifier authentication (and by extension knowing who to respond to) in something like a trust ping protocol.

**Comment by swcurran** [comment]
I'm not sure about this:

Is "from" required on all messages or just when establishing or changing the DID for a connection?  I had been thinking that receiving the message requires determining on what connection the message arrived, and therefore to whom the response should go.
