### ISSUE TITLE
Out of Band is out of date

### ISSUE THREAD

**Issue by brianorwhatever** [decentralized-identity/didcomm-messaging#282]
I think the [Out of Band](https://identity.foundation/didcomm-messaging/spec/#out-of-band-messages) protocol is outdated as it does not follow didcomm v2 syntax. I think all that is required is moving the `goal`, `goal_code` and `accept` properties into a `body` object. Is there anything else required to get this up to date?

**Comment by kdenhartog** [comment]
Ideally - I'd like to rename it and consider how we can better align it a bit better with the ideas I laid out in #250 even though I'm bought into the idea raised by @TelegramSam that we should keep connection setup and connection management separated
