### ISSUE TITLE
Why epoch time over ISO 8601?

### ISSUE THREAD

**Issue by brianorwhatever** [decentralized-identity/didcomm-messaging#284]
Is there rationale behind that decision? I much prefer the readability of ISO 8601 and of course theres the Year 2038 problem with epoch..

I'm talking specifically about `created_time` and `expires_time`

**Comment by kdenhartog** [comment]
Original reason for JWM using that was cause that's what JWTs use. Not sure why they picked epoch time format though.

**Comment by brianorwhatever** [comment]
That makes sense. DID Core uses ISO as another datapoint. JWT probably leaned epoch for smaller data size reasons
