### ISSUE TITLE
Signed Messages needs to require the `to` header

### ISSUE THREAD

**Issue by AnomalRoil** [decentralized-identity/didcomm-messaging#289]
Currently the "to" field is optional, but when doing "sign then encrypt", it is a good practice to **mandate** the use of a signed "to" field, in order to avoid tricky issues and attacks.

See e.g. [world.std.com/~dtd/sign_encrypt/sign_encrypt7.html](https://theworld.com/~dtd/sign_encrypt/sign_encrypt7.html)  for more details about what could go wrong.

Currently the specs says:

> When a message is both signed and encrypted, the plaintext is signed, and then the signed envelope is encrypted. The opposite order is not used, since it would imply that the signer committed to opaque data (which is unsafe and undermines non-repudiation).

(Notice this isn't using requirement terminology, we might want to use a "The opposite order SHALL NOT be used" instead?)

And also:

> A DIDComm message can be signed, either in conjunction with encryption or independently if the message will remain unencrypted.
> 
> If a message is signed and encrypted to add non-repudiation, it must be signed prior to encryption.

Let's make the "to" field mandatory when we are doing "sign then encrypt" in order to avoid relay attacks or replay attacks or other nasty issues.

A few more things:
- For a signed broadcast message, we might want to mandate a "created_time" timestamp instead and a "to" field that says it is a broadcast? Or should we add in the "verification" section that a message that is lacking a "to" field and is signed should be automatically treated as a broadcast?
- Arguably, authcrypt isn't vulnerable to "surreptitious forwarding" since it's authenticating the sender, but in the anonymous case, or with an ephemeral DID, this isn't the case... So I'd argue it's still a concern.
- Encrypt then sign requires the "from" attribute to be encrypted, which is now required as of #274, so we're fine on that front, although it's currently not supported by the spec, and so it's currently more secure than the Sign then Encrypt we're mandating...

**Comment by kdenhartog** [comment]
In a sign then encrypt (nested) message I believe we're covered here because the from value should match to authorized keys in the did document that were used for signing and key agreement.

If we were to only sign the message then we'd encounter this issue as well, but there's certain cases where it makes sense to sign with no intended audience such as signed proof requests in a 0-RTT flow for VC-Authn. 

For this reason, I think it makes sense to stick with a SHOULD in this scenario where implementations should be including the to value, but there's good reasons not to in certain cases and we can detail this should in the implementation guide.

**Comment by AnomalRoil** [comment]
Yes, this totally also applies to "just" signed message, I'm fine with adding a SHOULD statement recommending a "to" field when a signature is used.
Can I submit a PR for that change?

**Comment by kdenhartog** [comment]
Yeah let's start with a PR, so I can get a better understanding of the specifics that you're seeing are a problem here. I'm thinking this may already be covered by the required matching of the `from` to the sign `kid` and the encrypt `skid`. For example if Mallory received a message from Alice and tried to forward it to Bob, the `from` value would be Mallory's DID, the `skid` would be a key associated with the DID, but the `kid` in the signed message would be the key that's associated with Alice's DID.


but... I just realized there is a way to circumvent that check. If Mallory were to add Alice's key to her DID Document then she could make it validate all properly. This would make it possible for Bob to recognize that the message originally came from Alice, but without the `to` value being required then he wouldn't be able to detect that the message wasn't originally authored to him. So I agree this is a problem where we do need to require the `to` value to solve this.

**Comment by AnomalRoil** [comment]
Done @kdenhartog, please have a look at #296

**Comment by TelegramSam** [comment]
@kdenhartog any thoughts on the merged PR?
