### ISSUE TITLE
Why is P-256 deprecated?

### ISSUE THREAD

**Issue by AnomalRoil** [decentralized-identity/didcomm-messaging#292]
I've already touched on the topic in #243, especially in https://github.com/decentralized-identity/didcomm-messaging/issues/243#issuecomment-890029722 but the rest of the issue hijacked the question.

Mandating P-384 and deprecating P-256 over P-384 doesn't necessarily make sense in my opinion.
X25519 and P-256 both have a security level of ~120-128 bits.
P-384 has a security level of ~192 bits.
So it doesn't make sense to deprecate P-256 but not X25519... If you want a larger security level you should also deprecate X25519.
P-384 is also far less used and thus optimized in software and hardware implementations, which means it is slower than the more classical P-256 curve.

I've already posted many benchmarks in #243, but let me re-add this one:
```
p256::generate_key_pair                  bench:   9,665 ns/iter
p256::gen_key_pair_and_agree_ephemeral   bench:  51,820 ns/iter

p384::generate_key_pair                  bench: 362,917 ns/iter
p384::gen_key_pair_and_agree_ephemeral   bench: 708,025 ns/iter

x25519::generate_key_pair                bench:  19,816 ns/iter
x25519::gen_key_pair_and_agree_ephemeral bench:  73,051 ns/iter
```

I don't see the rationale behind this choice and wouldn't recommend it. Actually removing P-384 would make things simpler, since it's not an algorithm that is necessarily available in all libraries of platforms, unlike P-256.
(But it would limit DIDComm to a 128 bit level, agreed, which is not necessarily desirable neither.)

The security level of all the symmetric encryption primitives is at 256 bits, so we're only limited by the key exchange currently. But key-exchange is a CPU intensive operation, especially at higher security levels.

I would also recommend adding a section about allowing the use of a pre-shared key, so that DIDComm is able to reach its complete 256 bit security level using out-of-band key sharing, unlike with any current key-agreement option. This is already discussed in #255.  
This would also ease the implementation of "session" on top of DIDComm. (As per § 1.3.2, "sessions can _easily_ be built atop it", which isn't the case currently as it would require designing an alternative protocol to store the ciphertext in the body part of a DIDComm plaintext message, or something similarly strange...)

So, why P-384 as a default and not P-256?
I would recommend against deprecating P-256.

**Comment by kdenhartog** [comment]
P-384 is selected to meet NIST compliance more globally. In New Zealand, the baseline requirement curve to be used is P-384 while in many other countries they have more options. So the general thinking was that rather than having to support P-256 and P-384 we'd just support one that cross cuts more.

**Comment by TelegramSam** [comment]
Discussed in WG 20211213.
