### ISSUE TITLE
Is P-521 missed? 

### ISSUE THREAD

**Issue by asmarty** [decentralized-identity/didcomm-messaging#298]
The section "5.4 Key Wrapping Algorithms" describes algs with P-521 NIST defined elliptic curve.

<img width="933" alt="Screenshot 2021-10-04 at 01 35 14" src="https://user-images.githubusercontent.com/87315034/135830948-728e160a-960a-4f73-a8d1-756d7f496760.png">

But in the section "5.3. Curves and Content Encryption Algorithms" this curve is missed. 

<img width="830" alt="Screenshot 2021-10-04 at 01 34 24" src="https://user-images.githubusercontent.com/87315034/135831182-c08e4aac-7bd5-461d-97ec-3d51eb7580df.png">

**Comment by TelegramSam** [comment]
@Baha-sk @troyronda ?^

**Comment by TelegramSam** [comment]
discussed in WG meeting 20211004. @kdenhartog to work on it with @Baha-sk to make up a PR that makes this consistent.

**Comment by Baha-sk** [comment]
I guess P-521 is there because it's NIST, but it wasn't added in the list of official curves supported because of the nature of IOT devices.

I think we can add P-521 to the list of curves for now and implementers can decide what types they'd like to support.

**Comment by kdenhartog** [comment]
Yeah we mentioned on the call that it's probably best to do a required/optional approach and then let things fall where they may. Otherwise we're likely to just keep revisiting this topic each time it's brought up.

**Comment by AnomalRoil** [comment]
Please, while you're at it could you fix the "256 bits key" in the key wrapping table since we are actually using A256CBC-HS512 which requires 512-bit keys, not 256 bits.
