### ISSUE TITLE
Discover Features Update

### ISSUE THREAD

**Issue by TelegramSam** [decentralized-identity/didcomm-messaging#301]
This discover features protocol in the spec is behind the newest version defind in the Aries community. Should we update this to take advantage of the stuff learned over there? Also, if changes are made, perhaps we should rev the version on the protocol.

**Comment by dhh1128** [comment]
Yes. I'll add a PR about this to my to-do list.

**Comment by TelegramSam** [comment]
Closed, per merged PR.
