### ISSUE TITLE
`typ` specified in plaintext message format?

### ISSUE THREAD

**Issue by TelegramSam** [decentralized-identity/didcomm-messaging#317]
Several places in the spec have `typ` specified in the plaintext form of the message. I think this is quite redundant, as you already can understand the format because you have to look there to see the `typ` attribute.

**Comment by TelegramSam** [comment]
@AnomalRoil makes this observation in #290 and we are leaving it for this ticket to solve.

**Comment by apelt** [comment]
Well, that is why [typ](https://identity.foundation/didcomm-messaging/spec/#message-headers) is optional now, right? I think this can be closed now.
