### ISSUE TITLE
Large review of the current spec

### ISSUE THREAD

**Issue by AnomalRoil** [decentralized-identity/didcomm-messaging#321]
I've gone through the entire spec as it currently is and have written a lot of comments, as well as found a lot of typos and dead links, which I've ended up summarizing in a HackMd document here: https://hackmd.io/@AnomalRoil/HkJf7WcEt

Overall my main items are:
- lots of editorial comments
- the spec is currently often missing normative terminology "MUST", "SHOULD", etc.
- some of it needs to be rephrased to be clear/understandable
- the whole spec is currently not clear whether Anoncrypt is still a thing or if PeerDID should be used with Authcrypt to achieve Anoncrypt. See #153, but the rest of the spec is still containing mention of it.
- the `alg` field could be delegated to the ECDH-1PU
- #289 -> need to require the `to` header. Merged.
- #290 
- #291 
- #292 -> closed after WG 20211213 
- #298 
- #303 
- the "extra" protocols should be moved to their own spec, IMO (OOB, Trust Ping, Discovery, ...) 
- #243 
- "goal codes" are unimplementable given the current spec, their use and how they work both aren't properly described.
- There are lots of TODOs in the published spec.
- #323 -> fixed found typos

**Comment by AnomalRoil** [comment]
@TelegramSam @kdenhartog @dhh1128 ^

**Comment by OR13** [comment]
we also have ~60 open issues.

typically before publish all the issues need to be marked as deferred or resolved.

**Comment by mccown** [comment]
I read through the review and there are a lot of great comments, fixes, suggestions, etc.  Since this issue addresses so many items, what's the best way to start making (and specifically tracking) the suggested changes -- presuming that they won't be done all at once?

**Comment by TelegramSam** [comment]
Discussed WG 20220502. Thanks both for the review and the changes that it motivated.
