### ISSUE TITLE
Secure Connections in Apple Platforms (App Transport Security)

### ISSUE THREAD

**Issue by mccown** [decentralized-identity/didcomm-messaging#345]
While most of the examples in the DIDComm Spec & Guide show URLs as _https_, some are shown with _http_.  One example is in [Section 9.5: DID Document Service Endpoint](https://identity.foundation/didcomm-messaging/spec/#did-document-service-endpoint).  

Despite security issues, this can be a problem for Apple platforms, which have a feature called App Transport Security (ATS).  By default, ATS validates URL requests and requires apps to make secure network connections (e.g., _https_) with insecure connections (e.g., _http_) being blocked.  ATS does allow developers to specify exceptions at build time (e.g., _NSExceptionAllowsInsecureHTTPLoads_), but they must submit a justification and may trigger an App Store security review.   For more details, see Apple's [Preventing Insecure Network Connections](https://developer.apple.com/documentation/security/preventing_insecure_network_connections).  

Based on this, I have a couple of questions:

1. To emphasize strong transport security, should these _http_ links be replaced with secure _https_ links in the documentation?  
2. Should the docs explicitly recommend _https_ over _http_?

**Comment by TelegramSam** [comment]
Discussed WG 20220328 - recommending https in all cases to avoid conflicts with mobile device practices.
Need to verify that spec includes this in examples and in the Transports section.
