### ISSUE TITLE
Out of Band Protocol 2.0 - Service, Handshake

### ISSUE THREAD

**Issue by apelt** [decentralized-identity/didcomm-messaging#347]
The [did:peer connection establishment](https://identity.foundation/peer-did-method-spec/#didcomm-approach) specifies usage of Out of Band Protocol. But only the [Out of Band Protocol 1.0](https://github.com/hyperledger/aries-rfcs/blob/main/features/0434-outofband) includes `services` [attribute](https://github.com/hyperledger/aries-rfcs/blob/main/features/0434-outofband/README.md#the-services-item) with `serviceEndpoint` and `recipientKeys` attr., and `handshake_protocols` attribute.

[Out of Band Protocol 2.0](https://identity.foundation/didcomm-messaging/spec/#out-of-band-messages) compliant with DIDComm v2 does not include `services` attribute, nor `handshake_protocols` attribute - both were removed. Please add these attributes so DIDComm v2 can be used also in **did:peer** (or **did:keri**) in order to establish connection between two parties, which doesn't have publicly resolvable DIDs (and where connection might be offline, e.g. when using BLE - Bluetooth Low Energy)

**UPDATE: see comment**

**Comment by apelt** [comment]
I decided to include the DID Document in the attachment of the _Out of Band Protocol 2.0 Invitation message_. Thanks to this the `services` and `handshake_protocols` attributes from v1.1 are not needed. 

**The agent logic is following:** It can now try to resolve the DID in `from` attribute with DID Resolver. If it is not resolvable the agent might look inside of the `attachments` to find a DID Document there. If found it goes on, if not problem-report is sent.

Please let me know if this is good approach - if yes, close the issue and consider mentioning the above logic in the documentation. This would be helpful for new comers. Thanks.

Note: #346 is also resolved thanks to this. The invitation receiver can include his/her DID Document in the attachment in the next message (e.g. [Issue Credential - Propose Credential](https://github.com/decentralized-identity/waci-didcomm/tree/main/issue_credential#propose-credential) or [Present Proof - Propose Presentation](https://github.com/decentralized-identity/waci-didcomm/blob/main/present_proof/present-proof-v3.md#propose-presentation))

**Comment by TelegramSam** [comment]
the service is not included in the OOB 2 as peer DIDs can be used for this purpose. did:peer numalgo 2 in particular i used for this. Attaching the did document will be considered non-standard.

**Comment by apelt** [comment]
You are right, did:peer numalgo 2 is a good solution, I am already using it. Therefore I am closing the issue. 

However, I must point out that _OOB 2 DID Document attachment_ could be used with _any_ other method. Also, it is more interoperable as existing and new methods would not have to create their own specific solutions.
