### ISSUE TITLE
DIDComm v2: mime-type vs media_type

### ISSUE THREAD

**Issue by apelt** [decentralized-identity/didcomm-messaging#350]
Is correct `mime-type` or `media_type`? Both occurs in the documentation - see attached image. It varies also in all examples.

![mediamimetype](https://user-images.githubusercontent.com/10205773/160101376-a5dac96d-eedc-46f4-8992-d121e750d853.png)

**Comment by TelegramSam** [comment]
Fixed in #363

**Comment by apelt** [comment]
There is still `mime-type` used instead of `media_type` in [chapter 9.4.2](https://identity.foundation/didcomm-messaging/spec/#invitation-httpsdidcommorgout-of-band20invitation). Otherwise it is ok :)
