### ISSUE TITLE
DIDComm documentation - "to" attribute

### ISSUE THREAD

**Issue by Vaplet** [decentralized-identity/didcomm-messaging#356]
- "to" attr - sometimes it is not in squeare bracelets [] as here https://w3c-ccg.github.io/universal-wallet-interop-spec/#example-33-sample-of-request-presentation-message-from-relying-party, but in the doc it says "it must be an array" here: https://identity.foundation/didcomm-messaging/spec/#message-headers

**Comment by brianorwhatever** [comment]
I opened this issue in that repo so closing this one
