### ISSUE TITLE
Move Tracing protocol to Protocols section?

### ISSUE THREAD

**Issue by TelegramSam** [decentralized-identity/didcomm-messaging#368]
https://didcomm.org/trace/1.0/trace_report as defined, but outside the protocols section?

**Comment by TelegramSam** [comment]
Discussed WG 20220418. Should move down to protocols section to be consistent. Refer to the new location from within protocols. Also, Problem Report?

**Comment by TelegramSam** [comment]
@dhh1128 ^?

**Comment by dhh1128** [comment]
I believe we decided that tracing would be an extension, outside the spec entirely.

**Comment by TelegramSam** [comment]
So, no. we don't need to move tracing to protocols.

This leaves Problem Report as the lone thing that might need to move.
