### ISSUE TITLE
Should we address MITM detection at all within DIDComm-messaging?

### ISSUE THREAD

**Issue by kdenhartog** [decentralized-identity/didcomm-messaging#41]
This is a placeholder issue just for me to dump a bit of information on the topic. I'll point people to it when I feel like there's enough information in here that it would warrant further discussion.

However at a high level, my thinking on this is that there's a few different topics that should be considered here.

1. Use of VCs at layer above (not handled in this spec). This is the way most of us have looked at it so far, and should be fine. It's similar to how TLS spec works around not defining cert authorities.

2. Use of VCs within this layer. As much as I'd like to see this handled at this layer , I don't think there's much appetite for this by others, so this is likely the least likely option.

3. Use of ascii art derived from keys exchanged in did documents. This doesn't seem relevant to this layer of the protocol because it requires UX/UI concerns, so seems probably not the best way to do it.

4. Use of multi-channel OOB checks. This one is probabilistic and likely has a lot of ambiguity that would make it hard to define, but ultimately is a promising approach that should at least be considered somewhere throughout the stack.

5. The new approach I've come across which seems like it could fit at this layer is detailed in [this paper](https://www.researchgate.net/publication/333443762_Password-Authenticated_Public-Key_Encryption) co-authored by Jan Camenisch. It seems promising because it requires only keys to work (no VC exchange needed), but the one caveat is the requirement of a shared secret (password) to be exchanged OOB. I'm becoming more and more convinced that this is an unavoidable aspect of decentralized key exchange. My understanding too is that the password is only used for authenticity of the key's exchanged through a commitment scheme, which means we can default to "untrusted" mode if the password fails and prompt users to do a VC exchange next.

Ultimately though with option 5 (the new one I've come across) I'm still trying to get a practical understanding of the implications of this. Hopefully others with experience in cryptography can take a look at this paper and help me evaluate it claims as well.

More to come on this later.

**Comment by TelegramSam** [comment]
Given that this topic lacks a clear answer, I suspect we'll be evaluating and trying various options for this over time. I think those attempts are far less disruptive at a higher layer. As we get smarter, we have the option to bring one back down to this layer in the future.

**Comment by kdenhartog** [comment]
> Given that this topic lacks a clear answer, I suspect we'll be evaluating and trying various options for this over time.

I agree

> I think those attempts are far less disruptive at a higher layer.

I agree

> As we get smarter, we have the option to bring one back down to this layer in the future.

That's the part I'm not comfortable with because it's not a common pattern shared with other secure communication protocols (TLS, QUIC, WebRTC, signal) I've seen them all addressed in that bottom key exchange layer by at least setting up the extension point for certificates.

Main reason I even brought this up again though is because option 5 is a new method for handling this and it relies only on the keys and a shared secret. Meaning the VC layer remains decoupled (VC exchange still operates at a higher layer) while still being able to detect a MITM attack at the did exchange layer. To a certain degree, you'd be able to identify them because you know who you shared the secret with (which provides the authenticity guarantees), but it wouldn't be the same as what could be gotten with a VC layer.

With that in mind, let's keep moving forward and this is issue will be the parking lot for that side discussion until we decide we know enough to decide how to solve it.

**Comment by swcurran** [comment]
@kdenhartog - could you explain the interactions that allow option 5 to work?  Assuming the underlying cryptography is right, what do Alice and Bob have to differently than what we've talked about so far?  Notably, is a separate channel needed to send the password between the two?

I looked through the paper and I didn't get that.

**Comment by kdenhartog** [comment]
> Notably, is a separate channel needed to send the password between the two?
Yes, this is the key difference that would bubble up to the protocol layer. At least as far as I understand it right now.

It's the password that's used to generate a key so that the data can be validated by both parties. It's essentially using a KDF function on the password to generate a shared symmetric key that can be used with a Password Authenticated Key Exchange (PAKE) to validate the authenticity of exchanged of data. The notable difference from what I have gathered so far is that this key can only be used once within the protocol. If the password fails, then the protocol fails essentially. 

However, the part I'm still confused about is the statement:

> PAPKE enables secure end-to-end encryption between two entities without relying on a trusted third party or other out-of-band mechanisms for authentication

This seems in direct conflict with my understanding of the password needing to be shared OOB, hence my uncertainty. In the paper it says: 

> Relation to PAKE. To better understand the strength of the PAPKE prim- itive we compare it to the well-studied primitive of Password-Authenticated Key Exchange (PAKE) [8, 13, 18] The relation between PAPKE and PAKE is two- fold. First, PAPKE immediately implies a two-round PAKE: Alice and Bob can perform password-authenticated key exchange if Alice sends to Bob a PAPKE public key authenticated by her password, and Bob encrypts a session key using the received key and his password. Indeed, we show that if this simple proto- col is instantiated with any scheme satisfying our UC PAPKE notion then the resulting protocol satisfies the strong UC notion of PAKE [18]

Which leads me to believe that Alice and Bob wouldn't need to share a password, but rather could use their own password to validate the shared secret. Again, not sure what's going on here. Only reason I brought it up is because it seems like a promising technique worth getting more eyes on.

**Comment by Diiaablo95** [comment]
I personally think that a temporary (lower-quality) solution is better than no solution. This is not a small issue, and it should be addressed. One dirty solution is already there, VCs, which could be used in the same way TLS does with certificates. Then, if a better solution is found like the one proposed in the PAPKE paper, it could be replaced. Otherwise it opens the way to many faulted implementation from people that think DIDComm is secure, when it is not...

**Comment by kdenhartog** [comment]
The interesting thing about TLS is that they set criteria for certificates, but don't establish how they are used to produce a "trusted" connect. The root CA system happens as a consideration outside the spec. If we were to go that route @Diiaablo95 what would you suggest as a change for this? 

I for one would love to see us address this problem at this layer as well and share your concern that this isn't a small issue. With that in mind, I think we've lacked the clarity and confident understanding as a community on how to solve this issue because we haven't found the answer to what the actionable text should look like that addresses the concerns.

**Comment by Diiaablo95** [comment]
Well, the way I see it, is that there is a gap that needs to be filled, namely proving that whatever presentation you are delivering, it needs to be linked to the DID that is being used in the connection creation. I have to say that I am not an expert on crypto, and that I am not an expert of Hyperledger Indy/Aries/Ursa either. I have been working with it for a year, but still do not fully grasp all the nitty-gritty details, so please correct me if I am saying something incorrect or am assuming something that is not true.

The way we are temporary solving the issue in our case, which, as I mentioned in [this issue](https://github.com/hyperledger/aries-rfcs/issues/473), is based on Bluetooth communication between two untrusted parties, is to require both parties to include in the proof a "certification" from some third-party authority about the DID (or just some public key) being used in the connection creation. If the certified DID and the used DID are different, then of course it does not make sense to proceed further. This, of course, has several drawbacks both in terms of scalability and privacy. The most "logical" option for me (but I do not know how feasible it is), would be to include a self-attested attribute in the proof the links the other pieces of the proof to the DID used.
We have also seen in our measurements that using ZKPs (both generation and verification) is very time-consuming for the types of agents involved, hence the option of using ZKPs to prove inclusion of a DID in some kind of well-known set is out of discussion, at least for now. I guess it would probably work similarly as with the revocation registries for revocable credentials.

But coming back to the point I raised in my previous comment, I see many more peer-to-peer interactions between untrusted parties, than between trusted parties. So a way, even if rudimental, to allow those parties to establish a trusted channel needs to be in place, somehow.

**Comment by nikosft** [comment]
> 5. The new approach I've come across which seems like it could fit at this layer is detailed in [this paper](https://www.researchgate.net/publication/333443762_Password-Authenticated_Public-Key_Encryption) co-authored by Jan Camenisch. It seems promising because it requires only keys to work (no VC exchange needed), but the one caveat is the requirement of a shared secret (password) to be exchanged OOB. I'm becoming more and more convinced that this is an unavoidable aspect of decentralized key exchange. My understanding too is that the password is only used for authenticity of the key's exchanged through a commitment scheme, which means we can default to "untrusted" mode if the password fails and prompt users to do a VC exchange next.

Jan Camenisch has many patents in this area. Before starting implementing anything I would suggest to check with him if any related patent has been filed.

**Comment by kdenhartog** [comment]
Was just reviewing some reading on this subject again and I came across a term for how we're using DIDs with VCs at the moment. 

It's "Blind Trust Before Verification" and it's a model shared by XMPP.

**Comment by dhh1128** [comment]
I vote that we don't address this at all, and that we explicitly say so in the spec.

In the physical world, there is supposedly a "red line" phone between the desks of some world leaders (e.g., the Kremlin and the prime minister of the UK at #10 Downing). This line guarantees that there is no snooping on the line; everything is encrypted and no unsafe routing happens between the two endpoints. But it does NOT guarantee who picks up the phone; the Prime Minister's personal secretary might do that, and so might a little kid who came to tour the PM's office and who grabbed the phone unexpectedly. The people who worry about the secure line don't try to solve the "who picks up the line" problem with wiring used for red phones; they defer that to a different level.

DIDComm provides secure pipes. The meaning of the word "secure" in that phrase is NOT "guaranteed to be the person you intended" but rather "tamper-proof and confidential." It's the job of a different layer to prove that you're talking to the person you intended.

**Comment by TelegramSam** [comment]
Discussed briefly in 2020-05-11 WG Call. The only comment was that this layer is not the right layer to solve it. DIDComm aims to provide a 'red phone' that guarantees nobody can listen in, but provides no guarantees about who picks up the phone on the other end. (hat tip @dhh1128)

**Comment by nikosft** [comment]
Somehow you are missing the MITM problem: it is not about who picks up the phone--this is authentication, it is about somebody cutting the line in two parts and placing him/her self in between. Even if the correct person picks up the phone, you still have a problem!

**Comment by swcurran** [comment]
Daniel, Sam -- I believe what @nikosft is talking about is the problem where someone is between the two parties at initiation of the connection, and acts as a proxy between the two for the length of the connection -- by proxying proof requests and proofs.  If that last part was detectable - being able to detect a proxy between a proof request/response, it would be sufficient, but AFAIK, that is not detected with the current mechanisms.


We talked about this in the Aries work and decided that (a) it was an edge case that we were OK with leaving for now because (b) there was some proof request/proof changes coming in Indy that would detect the MITM.  Given we want to agnostic to the proof request/proof formats, how do we detect that?

**Comment by TelegramSam** [comment]
I assure you both @dhh1128 and I understand the MITM problem. No analogy is perfect, and you appear to have applied it beyond what was intended.

MITM detection is easy with an out-of-band verification, really hard without it. We've heard loose ideas for in-band detection, but no concrete suggestions. Out-of-band detection is usually accomplished over the already established connection, which would look like a protocol in our case.

We'd love to hear details about how it can be accomplished without undue violence to the goals and layered approach we've begun.

**Comment by swcurran** [comment]
The proposal I had heard was along these lines.  A proof would include a a self asserted, signed claim of the DID being used for the connection that is linked to a credential issued to the prover.  That would bind the communication path to a credential used for identity. 

Since a MITM proxying the message cannot alter the proof, the use of a different connection to prepare and send the proof would be detected.

**Comment by dhh1128** [comment]
@nikosft and @swcurran : I don't think I'm misunderstanding at all. I think the problem that's making us talk past each other stems from a difference in starting assumptions. Suppose you frame the problem like this:

>Alice wants to talk to Bob. She opens a channel to Bob. But Malfoy could be in the middle, proxying Alice to Bob and Bob to Alice.

Framed this way, we have a classic MITM attack. It's undeniable.

But I claim the problem has been framed wrong, so the conclusion stems from a false premise. The sentence "She opens a channel to Bob" is illegal. What I am claiming is that there is no such thing as "open a channel to Bob." There is only "open a channel that might be to anybody." The guarantee of the channel can never be more than that, unless (as @nikosft points out) the channel adds authentication of Bob-ness. And our channel doesn't do that, in and of itself. This is DIDComm, not Bob-comm. It guarantees the DID of the party you're talking to. Whether that DID belongs to Bob or not is outside the scope of its concerns.

The question of whether a particular DID controller is really Bob is a question for VCs. DIDComm gives you a tamper-proof, confidential pipe to some DID. That's it. A very useful and logical thing to do, after you have that pipe, is ask the DID controller to prove they are Bob. Alternatively, if you know *before* you open the channel that Bob controls the DID, you're also good. If you do either of these checks, then you know you're talking to Bob. If you don't, then you don't. It's as simple as that.

Re. @swcurran 's question about proxying credential proofs: this is possible, but only if the proof requests are sloppy. Consider the following conversation:

>Alice to unknown remote party: "Please prove that you're Bob."
>unknown remote party: "Sure, here's a credential that says so."

How does Alice decide if the proof is adequate? She has to guarantee that the credential she is seeing, that proves Bob-ness, is truly bound to the party she's talking to, not to a shadowy MITM. In other words, if the conversation that's really happening looks like this, it needs to fail:

>1. Alice to Malfoy as fake Bob: "Please prove that you're Bob."
>2. Malfoy to Bob, re-encrypting so sender = Malfoy's fake AliceDID: "Please prove that you're Bob."
>3. Bob to Malfoy as fake Alice: "Sure, here's a credential that says so."
>4. Malfoy to Alice, re-encrypting so sender - Malfoy's fake Bob DID: "Sure, here's a credential that says so."

The technique Stephen mentions above will work. If step 3 includes an assertion of Bob's DID, signed by BOB's DID, <u>AND</u> if that assertion is indivisible from the rest of the credential, then Malfoy can't tamper with it and can't simply play it back to Alice without being detected. Note the proviso; if the self-assertion is separable, Malfoy can just pull off the old one and substitute a new one.

There are other possible techniques. What I believe they all have in common is that they rightly belong at the level above DIDComm.

**Comment by swcurran** [comment]
I agree with the first part about DIDComm's concern.  Good there.

What I still don't know is how the second technique is done in arbitrary credential/proof formats.  But, since it is at level above DIDComm, it's not really a concern of DIDComm.

I do think it is worth including the DIDComm spec at least the pretty concise description we've arrived at above as a requirement of the higher levels of the stack to accomplish to prevent MITM attacks -- the need to bind whatever claims are sufficient for identity with the DIDComm connection being used to convey the that information.

That said, since we need to bind a claims about the DIDComm connection to the identity claims, could DIDComm provide a recommendation on how to do that?

**Comment by dhh1128** [comment]
I think a brief section about this topic would be good -- basically explaining the reasoning we've developed, and presenting a simple recipe for how to do it correctly.

For the record, here's how to do this correctly in Indy today:

1. The prover and the verifier both agree on inputs to something called a "challenge hash." Today, the content of the challenge hash is a nonce, randomly chosen. But if both prover and verifier agree that it should be a nonce, randomly chosen, PLUS the prover's DID, then they can do that today without any changes to library code. They've just modified a single numeric input to a function call.

2. The verifier evaluates all the other characteristics of the proof, but also verifies that the challenge hash they calculated matches the challenge hash that the prover generated. This will only be true if they both have the same view of the prover's DID (i.e., no MITM).

How to do it correctly if you're not using Indy is a bit complicated. Most people in the ecosystem have not acknowledged, yet, the need for a proof request that includes a nonce; they believe they can just show a credential. The problem with this, quite aside from MITM concerns, is that you can drive a truck through the replay attack vulnerability. Any bits that contain a credential can be replayed by anyone--even someone who can't see inside an encrypted channel--at any time to simulate a new proof.

So let's assume people eventually come around to the idea that at least a nonce is needed. Now, if the nonce mechanism is robust, AND if the disclosed credential includes a DID for the credential subject that also happens to be the DID being used to secure the DIDComm channel, then you're good. But the second condition here is not likely to be generally true: Alice isn't required to use the same DID everywhere, including for DIDComm, that she used to get a passport. She's just required to prove control over whatever DID is in that passport.

This means that the safer and more general solution for non-Indy creds is the solution Stephen already recommended: require a signature by the DIDComm prover's DID, over the proof presentation that includes the DIDComm DID of the prover. And separately require a signature over the proof presentation by the DID inside the VC, if it's different. How those two signatures are related is TBD. A bit ugly.

Maybe we should update RFC 0037 or its successor to cover this in greater detail.

**Comment by kdenhartog** [comment]
> 
> 
> @nikosft and @swcurran : I don't think I'm misunderstanding at all. I think the problem that's making us talk past each other stems from a difference in starting assumptions. Suppose you frame the problem like this:
> 
> > Alice wants to talk to Bob. She opens a channel to Bob. But Malfoy could be in the middle, proxying Alice to Bob and Bob to Alice.
> 
> Framed this way, we have a classic MITM attack. It's undeniable.
> 
> But I claim the problem has been framed wrong, so the conclusion stems from a false premise. The sentence "She opens a channel to Bob" is illegal. What I am claiming is that there is no such thing as "open a channel to Bob." There is only "open a channel that might be to anybody." The guarantee of the channel can never be more than that, unless (as @nikosft points out) the channel adds authentication of Bob-ness. And our channel doesn't do that, in and of itself. This is DIDComm, not Bob-comm. It guarantees the DID of the party you're talking to. Whether that DID belongs to Bob or not is outside the scope of its concerns.
> 
> The question of whether a particular DID controller is really Bob is a question for VCs. DIDComm gives you a tamper-proof, confidential pipe to some DID. That's it. A very useful and logical thing to do, after you have that pipe, is ask the DID controller to prove they are Bob. Alternatively, if you know _before_ you open the channel that Bob controls the DID, you're also good. If you do either of these checks, then you know you're talking to Bob. If you don't, then you don't. It's as simple as that.
> 
> Re. @swcurran 's question about proxying credential proofs: this is possible, but not if the proof requests are careful. Consider the following conversation:
> 
> > Alice to unknown remote party: "Please prove that you're Bob."
> > unknown remote party: "Sure, here's a credential that says so."
> 
> How does Alice decide if the proof is adequate? She has to guarantee that the credential she is seeing, that proves Bob-ness, is truly bound to the party she's talking to, not to a shadowy MITM. In other words, if the conversation that's really happening looks like this, it needs to fail:
> 
> > 1. Alice to Malfoy as fake Bob: "Please prove that you're Bob."
> > 2. Malfoy to Bob, re-encrypting so sender = Malfoy's fake AliceDID: "Please prove that you're Bob."
> > 3. Bob to Malfoy as fake Alice: "Sure, here's a credential that says so."
> > 4. Malfoy to Alice, re-encrypting so sender - Malfoy's fake Bob DID: "Sure, here's a credential that says so."
> 
> The technique Stephen mentions above will work. If step 3 includes an assertion of Bob's DID, signed by BOB's DID, AND if that assertion is indivisible from the rest of the credential, then Malfoy can't tamper with it and can't simply play it back to Alice without being detected. Note the proviso; if the self-assertion is separable, Malfoy can just pull off the old one and substitute a new one.
> 
> There are other possible techniques. What I believe they all have in common is that they rightly belong at the level above DIDComm.

Can we stick with a standard security definition? I propose we use Definition 1 from this paper: https://iacr.org/archive/eurocrypt2001/20450451.pdf

**Comment by dhh1128** [comment]
Kyle: Could you be more specific? Not about the definition; that is quite clear. But about where you want to apply it? Are you saying that you want to view all of DIDComm as a key exchange protocol -- or only the DID exchange protocol as a key exchange protocol? What are you mapping onto the construct of session keys?

**Comment by kdenhartog** [comment]
@swcurran
>That said, since we need to bind a claims about the DIDComm connection to the identity claims, could DIDComm provide a recommendation on how to do that?

To address our concerns around saying VCs exist at another layer, I think we state it similarly to how [appendix C.5](https://tools.ietf.org/html/rfc8446#appendix-C.5) of the TLS 1.3 spec states it.

**Comment by kdenhartog** [comment]
> 
> 
> Kyle: Could you be more specific? Not about the definition; that is quite clear. But about where you want to apply it? Are you saying that you want to view all of DIDComm as a key exchange protocol -- or only the DID exchange protocol as a key exchange protocol? What are you mapping onto the construct of session keys?

Yes, this would only apply to DID exchange protocol.

Session key's would be the key's used to encrypt the content encryption key in the JWE, which in our case are long term session keys.

**Comment by kdenhartog** [comment]
> Most people in the ecosystem have not acknowledged, yet, the need for a proof request that includes a nonce; they believe they can just show a credential.

In the case of CHAPI which uses [verifiable presentation requests](https://digitalbazaar.github.io/vp-request-spec/#format) this is the challenge field so they're good. In the case of JWT credentials, I've not seen a proposed format enough to work with it and say whether they are addressing it. Would be happy to look through one if people suggest them to me here though.

**Comment by kdenhartog** [comment]
Also to be clear, my position still resonates with the notion of "not this layers concern". If we were to somehow add it in at this layer, I'd recommend option 5 only at this layer, but I'm not confident in this option well enough that I could write the language to add it in. So I think we stick with we make a recommendation of how it should be addressed at a separate layer with VCs.

**Comment by Diiaablo95** [comment]
So how impractical would be to include a signature that would cover both credential-derived attributes and self-attested attributes? Is that the change coming with schemas 2.0? What is the expected roadmap for that?

From my humble point of view, I know that the word security includes, among the others, authentication, confidentiality, and integrity. If some of this properties are missing from a secure channel, then it is not a secure channel. We can't call a DIDComm-based channel secure if it cannot guarantee the authenticity of the two parties communicating. That is why I think any solution to address this issue should be part of this level, because it is about the parties that are communicating. Any additional information that is needed at application level would make sense to include in the VC layer. But I have hard times thinking that some applications might not want to have a communication channel that does not provide authenticity of the actors.

**Comment by kdenhartog** [comment]
> 
> 
> So how impractical would be to include a signature that would cover both credential-derived attributes and self-attested attributes? Is that the change coming with schemas 2.0? What is the expected roadmap for that?
> 
> From my humble point of view, I know that the word security includes, among the others, authentication, confidentiality, and integrity. If some of this properties are missing from a secure channel, then it is not a secure channel. We can't call a DIDComm-based channel secure if it cannot guarantee the authenticity of the two parties communicating. That is why I think any solution to address this issue should be part of this level, because it is about the parties that are communicating. Any additional information that is needed at application level would make sense to include in the VC layer. But I have hard times thinking that some applications might not want to have a communication channel that does not provide authenticity of the actors.

The difficulty in this approach is it introduces the question "What's enough information for the participating parties to know to get the guarantee of authenticity?". In the case of certificates, it's assumed that whatever domain the user chose, is the correct audience they intended to setup a channel with. What would be the analogous default VC request in a peer to peer relationship? Additionally, what happens if one or both parties don't have any VCs yet? These are the sticky questions that leads me to believe (what your arguing was my original position for quite a long time) it needs to be separate.

**Comment by Diiaablo95** [comment]
> what happens if one or both parties don't have any VCs yet?

The point here is that everyone should be on-boarded to the ecosystem via a secured bootstrapping procedure. Going up the chain, the issuance of the very first credential, for most of the non trivial use cases, will happen via a recognised public entity verify real-world documents and consequently issuing some sort of VC. From that point on, I do not see this as a major pain point.

**Comment by TelegramSam** [comment]
> We can't call a DIDComm-based channel secure if it cannot guarantee the authenticity of the two parties communicating. 

It's worth being clear about who the _parties_ are. Daniel above said:

> This is DIDComm, not Bob-comm. It guarantees the DID of the party you're talking to. Whether that DID belongs to Bob or not is outside the scope of its concerns.

And I agree. Applying credentials to verify the Bobness of the DID in use is very useful, but I believe it should not be part of this layer.

**Comment by TelegramSam** [comment]
Close in WG Meeting 2020-11-02
