### ISSUE TITLE
How do I know when I have a didcomm message vs a random JWE/JWS?

### ISSUE THREAD

**Issue by kdenhartog** [decentralized-identity/didcomm-messaging#54]
In processing a DIDComm message I can potentially have a few different messages that will pop off the wire. This logic can come quickly become quite complex to be able to identify the different options.

For example, the message off the wire can be a JWE or a JWS and those can be "DIDComm" formatted, or they could be for another implementation using the JOSE data structures + DIDs such as Secure Data Stores.

This leaves me wondering how we should verify key authorization for signing and key agreement to verify. Additionally what constraints do we need to put on this to make sure that the options we allow aren't leading to application vulnerabilities which I've heard was the case in previous identity protocols.

**Comment by TelegramSam** [comment]
I think being able to identify that what you received is a DIDComm message is quite important.

One option is that you don't mix endpoints between DIDComm and anything non-DIDComm. The expectation then is that anything you receive is a DIDComm message.

I still think it would be useful to easily identify a DIDComm message. This would be useful for trivial validation of messages you receive, as well as being able to differentiate based on type as you describe.

**Comment by TelegramSam** [comment]
As discussed in WG meeting 2020-05-25, context of receipt is the best way to manage this. Recent pr work includes language in the spec to this effect as a RECOMMEND.

**Comment by TelegramSam** [comment]
Closed in WG Meeting 2020-11-02.
