### ISSUE TITLE
should we use JCS and/or i-JSON?

### ISSUE THREAD

**Issue by dhh1128** [decentralized-identity/didcomm-messaging#58]
An interesting discussion on the W3C CCG mailing list has raised two topics that we may want to track re. DIDComm. See https://lists.w3.org/Archives/Public/public-credentials/2020May/0164.html.

* JCS is an IETF-sponsored JSON-signing mechanism that I had not previously known about? It appears to be compatible with JW* and includes simple canonicalization. I wonder if we should be using it?

* i-JSON (IETF RFC https://tools.ietf.org/html/rfc7493) is a tightened profile of JSON that improves interop. It eliminates some of JSON's fuzziness. For example, it specifies the largest and smallest possible integer values that are interoperable. It looks very easy to conform, to me; we might want to consider citing it or using it.

**Comment by OR13** [comment]
interesting, I had not heard of i-JSON

**Comment by csuwildcat** [comment]
I just talked with the JCS IETF draft author, and he says the draft is moving down the official ratification track soon. Given JCS has far better library support across multiple languages, I tend to prefer it.

**Comment by TelegramSam** [comment]
I'm a fan of both, though there are some issues to resolve between date formats and the JWM timestamp requirements (which are JW* style). 

Where is the right place to apply this within the spec?

**Comment by OR13** [comment]
IMO, it's better to just use JCS everywhere you would normally use JSON.stringify, and certainly anywhere you will be signing or hashing JSON, so that those signatures and hashes are stable... especially in places where the object might be constructed differently across language implementations...

**Comment by kdenhartog** [comment]
Does anyone remember what we wanted to use this for?

I'm thinking we can likely close this so going to mark as pending close.

**Comment by TelegramSam** [comment]
Closed via discussion in WG meeting 20210802. Please reopen if it should not have been resolved.
