### ISSUE TITLE
Add supported signature algorithm section

### ISSUE THREAD

**Issue by awoie** [decentralized-identity/didcomm-messaging#64]
Similar to encryption, we should also add a section on our supported JWS algorithm. We should also ensure that this is aligned with https://github.com/w3c-ccg/lds-jws2020

**Comment by OR13** [comment]
on the lds-jws2020 side we need to support the table defined here:  https://github.com/decentralized-identity/didcomm-messaging/pull/52/files/0c93942cfc50039eb5d14d8be0e714a1e702b94a#r436011960

It would be awesome to align lds-jws2020 signature algorithm recommendations with did comm as well.

**Comment by TelegramSam** [comment]
Closed in WG 20201109. @awoie reopen if disagree.
