### ISSUE TITLE
DID Rotation Signature Options

### ISSUE THREAD

**Issue by TelegramSam** [decentralized-identity/didcomm-messaging#65]
In WG Call 2020-06-08, we discussed using a detached compact jws as the `from_provenance` header attribute. The detached form makes the payload lighter by eliminating the double inclusion of the from and from_prior fields.

I've thought of an alternate approach: make the `from_prior` attribute a JWT, with sub: alice2, iss: alice. This eliminates the double inclusion, and also potentially makes it easier for the developer to validate the signature instead of skipping it. We also collapse two attributes into one, though with slightly more complexity inside the attribute.

Thoughts?

@dhh1128 @kdenhartog @tplooker @awoie

**Comment by dhh1128** [comment]
I don't have a strong opinion. Sounds like a good outcome to me.

**Comment by kdenhartog** [comment]
I think this is a good consolidation. I'm in favor of this approach.

**Comment by awoie** [comment]
Sounds good to me!

**Comment by kdenhartog** [comment]
Pretty sure this has been addressed. Marked as pending close @TelegramSam can you close if you agree?

**Comment by TelegramSam** [comment]
Closed via discussion in WG meeting 20210802. Please reopen if it should not have been resolved.
