### ISSUE TITLE
What are the Essential Protocols that should be included in the DIDComm spec?

### ISSUE THREAD

**Issue by TelegramSam** [decentralized-identity/didcomm-messaging#81]
Note, our charter ONLY includes specifying protocols necessary for establishing and maintaining the mechanics of DIDComm. Other protocols will be the work of other groups.

Proposed Essential Protocols:
- Trust Ping 
- Feature Discovery (please disclose protocols you support)
- Channel Teardown
  - I'm about to delete this DID and forget yours
  - Please erase my information (can serve as a GDPR erasure request)

Thoughts?

**Comment by bumblefudge** [comment]
+1 to GDPR erasure request-- making those machine-readable and automatable upon proof of DID control would a truly GDPR-compliant DID solution make. 

+1 to trust ping, that seems widely generalizable

As for feature discovery, I think maybe I missed (or was zoned out during) the part where feature discovery was discussed. Is that specific to a list of specified protocols in Aries or is that defined in a more cross-community way somewhere? or does that refer specifically to some forthcoming typology of service endpoints?

**Comment by swcurran** [comment]
It's a request for a list of protocols supported by the other entity (or perhaps entities) that run on top of DIDComm. It's implemented in Aries but is not limited by that, so it certainly can be cross-community.

**Comment by troyronda** [comment]
Note: there is already an essential protocol in the spec - Routing Protocol ( https://identity.foundation/didcomm-messaging/docs/spec/#routing). Also, are there other routing / mediation protocols planned for the spec?

Another [related topic](https://github.com/decentralized-identity/didcomm-messaging/pull/73#discussion_r453994310) is the aspects of out-of-band protocol that haven't yet been covered by spec text - Particularly goal code ("please play the role of").

**Comment by troyronda** [comment]
Beyond having a feature discovery mechanism for protocols, there is also the topic of lower layer metadata (and errors) such as supported DID methods. (#82).

**Comment by swcurran** [comment]
Cross-cutting protocols might be called essential.  I'm thinking in particular, adopted protocols (ack and problem report) and decorators -- threads, attachments, perhaps tracing.

**Comment by TelegramSam** [comment]
Closed in WG 20201109.
