### ISSUE TITLE
DIDComm Extensions & Last Mile bi-directional messaging.

### ISSUE THREAD

**Issue by TelegramSam** [decentralized-identity/didcomm-messaging#86]
DIDComm transports are one-way: messages only flow from the sender to the recipient. This provides a simple message flow for the majority of DIDComm interactions.

Some agents (smartphone apps and agents behind firewalls) are not capable of providing endpoints. Rather than providing for this case in the core spec, should we handle this in a DIDComm extension? We don't yet have the concept of extensions, but this seems like a good issue to figure out.

One of the benefits of this approach is that only agents that need this last-mile bi-directionality (in an interoperable way) need concern themselves with this extension.

Related question: How much interest is there within this WG in solving this problem in a standard way? Should that happen here, or left for another group to approach?

**Comment by TelegramSam** [comment]
Note: this would encapsulate the return-route type functionality within DIDComm v1

**Comment by OR13** [comment]
- https://ngrok.com/
- https://blog.alexellis.io/https-inlets-local-endpoints/

related for TCP/HTTP....

**Comment by TelegramSam** [comment]
@OR13 we've used ngrok for testing and demos, and have had issues. I don't believe this approach to be a stable solution for production applications.

**Comment by tplooker** [comment]
Also mildly relevant to the extend that this protocol aims to achieve a JSON messaging based protocol, all be it un-encrypted https://datatracker.ietf.org/wg/jmap/documents/.

**Comment by TelegramSam** [comment]
This got added as an extension here: https://github.com/decentralized-identity/didcomm-messaging/blob/master/extensions/return_route/main.md

Closing this now. Please reopen or create a new issue for any unresolved aspects of this issue.
