### ISSUE TITLE
DIDComm should recommend against unnecessary disclosure of services to the VDR

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/didcomm-messaging#94]
While its possible to resolve both a DID and a DID URL to a DID Document with a service suitable for didcomm...

We should prefer not to disclose services when possible to the VDR...

Reasons for not including services in VDR are documented here: https://github.com/w3c/did-core/issues/382

DIDComm should not prohibit the use of DIDs that publicly publish service endpoints (personal opinion, neither should DID Core....)., however we can recommend against ANY unnecessary disclosure outside of an encrypted channel... 

We can easily support both, and warn users about how if they publish their personal web server to bitcoin... its gonna be there forever.... with no ability to delete.... GDPR, considerations apply...

**Comment by OR13** [comment]
We should add a paragraph to the first part of DIDComm that describes what services are and how they are used, explaining this nuance.

**Comment by TelegramSam** [comment]
The cool part is that specifying a DIDComm endpoint doesn't disclose which DIDComm compatible protocols you support. This keeps the disclosure at a minimum at the outset. Protocol support can be shared, but only with the explicit action of the party, and only shared to a single party at a time.

We have some language in the spec now under discussion, but this may be moved to the guide.
